### ISSUE TITLE
Provide an uninstall.sh?

### ISSUE THREAD

**Issue by nekohayo** [fossfreedom/alternative-toolbar#1]
Not that I want to uninstall this plugin (it works pretty well :) but I thought it would be reassuring for users to have an uninstall script (for the conf schemas etc)?

**Comment by fossfreedom** [comment]
Probably should have another option ("-u") just like my other plugin

 - https://github.com/fossfreedom/coverart-browser/blob/release-2.0/install.sh

Could/should just copy the relevant uninstall function and call as per that script.
