### ISSUE TITLE
Traceback when enabling the plugin

### ISSUE THREAD

**Issue by didrocks** [fossfreedom/alternative-toolbar#105]
Hey,

I'm having a python Traceback when clicking on the application toolbar:
```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 351, in move_col
    remembered_col_titles = eval(element.text)
  File "<string>", line 1
    'Piste','Morceau','Genre','Artiste','Compositeur','Album','Année','Durée','Qualité','Note','Nombre de
lectures','Commentaire','Emplacement','Dernière lecture','Date d'ajout','BPM'
```

Any reason you are doing an eval? That doesn't play file for non ASCII string and isn't really safe. (I see the extension is using 3 evals).
Tell me if you need any other informations, I'm happy to test/help.

**Comment by fossfreedom** [comment]
its obviously a dirty way to parse all the column names held as a string in rhythmbox into a python array

it looks like its tripping over the column 'Date d'ajout' because of the extra french (?) apostrophe

need a better way to achieve this...

**Comment by fossfreedom** [comment]
ok - that commit will resolve this.
The other eval's are handling internal stuff so no need to worry.

**Comment by didrocks** [comment]
Confirmed that the patch fixed it and works well. Thanks for your swift answer :)
