### ISSUE TITLE
Options not easily accessible with modern UI

### ISSUE THREAD

**Issue by seb128** [fossfreedom/alternative-toolbar#108]
Using 0.17.4 on Ubuntu, when using the modern UI option (which is on by default) under GNOME the display/plugins/preferences options are in only the desktop integrated menu and not accessible from the rhythmbox main interface. The desktop menu isn't working great for GNOME and it was discussed at GUADEC about removing it since users don't always find it and it creates confusing, it would be nice if the toolbar plugin was putting an "hamburger menu" in the headerbar for the options like other softwares do

**Comment by fossfreedom** [comment]
I'm not aware of the discussions at GUADEC - is this at the GTK library level that the standard GTK (non CSD based) menu will be hidden/redisplayed somewhere, or is someone going to push a Rhythmbox code change?

**Comment by fossfreedom** [comment]
@seb128 BTW - is this what you are referring to?

    gsettings set org.rhythmbox.plugins.alternative_toolbar app-menu-display true

then run

    env XDG_CURRENT_DESKTOP=XFCE rhythmbox

**Comment by seb128** [comment]
There is no decision at the GNOME level about what to do with the appmenu yet but the upstream designers said that only non-essential-actions should be in there (e.g the about box) and other entries should be available from the UI. The GNOME applications do have the standard entries in a menu at the top right (firefox/chrome as well), why not doing the same?

**Comment by fossfreedom** [comment]
![workspace 1_075](https://user-images.githubusercontent.com/996240/29774059-02a9a2bc-8bf8-11e7-9265-98a39e0d26ef.jpg)

like this?

**Comment by seb128** [comment]
yes! :-)

**Comment by fossfreedom** [comment]
should now be resolved - needs a bit of testing to confirm

![workspace 1_080](https://user-images.githubusercontent.com/996240/30247477-cb457a6a-960d-11e7-94e5-059526d1788e.jpg)

![workspace 1_081](https://user-images.githubusercontent.com/996240/30247478-d19e1cc8-960d-11e7-9d3c-dd0475ad51e0.jpg)

(I'm using paper icons - switching to adwaita displays the traditional 3 horizontal line hamburger symbol)

**Comment by seb128** [comment]
That looks good!

**Comment by fossfreedom** [comment]
This has now been uploaded to Debian v0.17.5.

As such I will close this now. Thanks.
