### ISSUE TITLE
Sigabrt in rb_display_page_tree_select  when selecting "import error" in the sidebar

### ISSUE THREAD

**Issue by seb128** [fossfreedom/alternative-toolbar#112]
On Ubuntu artful
- have an android phone mounted in mpt (and not a lot of codecs installed?)
- click on the android device in the sidebar

-> there is a "import error" category add

- click on the label

-> rhythmbox hits an abort in rb_display_page_tree_select()

There is no such category displayed when selecting the device nor segfault without the "improved sidebar"option

Reported on launchpad as well
https://bugs.launchpad.net/ubuntu/+source/rhythmbox-plugin-alternative-toolbar/+bug/1723129

**Comment by seb128** [comment]
the backtrace retraced is available on https://launchpadlibrarian.net/340632076/Stacktrace.txt

The fact that the category is not displayed in the normal UI could hint that it's empty and shouldn't be listed/that's what creates the issue?

**Comment by fossfreedom** [comment]
please can I see the terminal output of

rhythmbox -D alttoolbar

**Comment by seb128** [comment]
The lines before the issue

(22:52:20) [0x7f1afc008640] [AltErrorsController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1013: RBImportErrorsSource
(22:52:20) [0x7f1afc008640] [AltToolbarSidebar._set_text] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_sidebar.py:1117: Sources en ligne
(22:52:20) [0x7f1afc008640] [AltToolbarSidebar._set_text] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_sidebar.py:1117: Sources en ligne
(22:53:01) [0x7f1afc008640] [AltToolbarSidebar._row_click] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_sidebar.py:960: _row_click
(22:53:01) [0x7f1afc008640] [AltToolbarSidebar._row_click] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_sidebar.py:970: <__gi__.RBImportErrorsSource object at 0x7f1adc01fb88 (RBImportErrorsSource at 0x55aa37eb6440)>
**
Rhythmbox:ERROR:rb-display-page-tree.c:497:rb_display_page_tree_select: assertion failed: (rb_display_page_model_find_page (display_page_tree->priv->page_model, page, &iter))

**Comment by fossfreedom** [comment]
@seb128 should be fixed with the above commit.

**Comment by seb128** [comment]
the changes indeed fix the issue, thanks

**Comment by seb128** [comment]
in fact the change seems buggy, the device had no music when getting the segfault. After adding some mp3 (and not having the corresponding codecs) the version without the change (or without the alternative toolbar plugin) displays an import error category for the phone, with the fix that isn't displayed

**Comment by fossfreedom** [comment]
hmm.  k - will look again.

**Comment by fossfreedom** [comment]
^^^ needs testing

**Comment by seb128** [comment]
The current version of the code seems to work fine, thanks for fixing the issue!

**Comment by fossfreedom** [comment]
@seb128 I've uploaded to debian mentors ... but if I don't hear anything before the 18.04 freeze date, I'll upload to ubuntu separately (I have upload rights for ubuntu).  I hope that's ok?

**Comment by seb128** [comment]
yes, that sounds good to me, thanks for taking care of it :)
