### ISSUE TITLE
Consider getting this merged upstream

### ISSUE THREAD

**Issue by afranke** [fossfreedom/alternative-toolbar#113]
This looks very good and I’m sure the maintainers would be interested in using at least some bits as the default. Why keep it as a plugin and not have it integrated upstream?

**Comment by fossfreedom** [comment]
@afranke upstream have no interest in this approach.  They have made this very clear.

They don't want a plugin - they want the changes built directly into rhythmbox.

**Comment by afranke** [comment]
Isn’t that what I’m saying though? Instead of a plugin, this should be in the core of the application.

**Comment by fossfreedom** [comment]
sure - I'm not a C developer - so cannot help upstream.
