### ISSUE TITLE
Stations string is untranslated

### ISSUE THREAD

**Issue by AsciiWolf** [fossfreedom/alternative-toolbar#114]
The "Stations" string is untranslated on non-English (Czech) Ubuntu 18.04 although it is translated in the pofile. It looks like the translation is not applied for some reason.

**Comment by AsciiWolf** [comment]
@fossfreedom Do you have any idea what could be the issue?

**Comment by fossfreedom** [comment]
yep - where we add/change the label of the buttons, the translation needs to be set to be from the plugin.

**Comment by AsciiWolf** [comment]
I see that _alttoolbar_controller.py_ is already present in POTFILES.in (and the Stations string is [already translated](https://translations.launchpad.net/alternative-toolbar/trunk/+pots/alternative-toolbar/cs/+translate?batch=10&show=all&search=Stations)).

**Comment by fossfreedom** [comment]
I suspect that here in  def set_library_labels(self, song_label=None, category_label=None):  https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_type.py line 1429

where we set_label from values obtained from altoolbar_controller we need to call get_text for the string https://docs.python.org/3/library/gettext.html to  find the equivalent translated string

**Comment by AsciiWolf** [comment]
Any news?

**Comment by fossfreedom** [comment]
Anyone is welcome to throw a pull request to resolve.

**Comment by fossfreedom** [comment]
should be resolved now.

**Comment by AsciiWolf** [comment]
It looks like that the "Repeat all tracks" string is also untranslated. Probably a similar issue.

**Comment by fossfreedom** [comment]
Please create another issue since this one is closed and the comment here will be likely missed in future. Cheers.
