### ISSUE TITLE
AppStream metainfo file

### ISSUE THREAD

**Issue by yotamN** [fossfreedom/alternative-toolbar#115]
In order to show on GNOME Software and other software centers that use AppStream the package needs a `.metainfo.xml` file. I made a file which I think is enough but it needs to be inside `%{_datadir}` and I'm not sure where it is in that project. In other projects that I looked at was in `data`.

```
<?xml version="1.0" encoding="UTF-8"?>
​<component type="addon">
​  <id>rhythmbox-alternative-toolbar</id>
​  <extends>rhythmbox.desktop</extends>
​  <name>Alternative Toolbar</name>
​  <summary>Enhanced play controls and interface</summary>
​  <url type="homepage">https://github.com/fossfreedom/alternative-toolbar</url>
​  <url type="bugtracker">https://github.com/fossfreedom/alternative-toolbar/issues</url>
  <url type="translate">https://translations.launchpad.net/alternative-toolbar</url>
​  <metadata_license>CC0-1.0</metadata_license>
​  <project_license>GPL-3.0</project_license>
​</component>
```

**Comment by fossfreedom** [comment]
Thanks for creating the file.

The makefile for the plugin is here https://github.com/fossfreedom/alternative-toolbar/blob/master/Makefile.am

$(datadir) is basically /usr/share so as far as I understand the metainfo.xml file needs to be in 
$(datadir)/metainfo/

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
