### ISSUE TITLE
Plugin isn't compatible with gtk-shell-show-menubar option.

### ISSUE THREAD

**Issue by ghost** [fossfreedom/alternative-toolbar#116]
I am using xfce with vala-panel-appmenu (Global Menu) . The gtk-shell-show-menubar option tells the application to not show the menu on the app window so it can be shown by the panel plugin . Is this by design ? If not,will you implement it ?

**Comment by fossfreedom** [comment]
Line 161 here shows how it uses the two variables to determine if it should use the CSD based interface or the compact interface - https://github.com/fossfreedom/alternative-toolbar/blob/master/alternative-toolbar.py

**Comment by IKRadulov** [comment]
If not using CSD the menu shows both in app and panel . If using CSD then the menu is only in app. I wan't for the CSD mode to show the appmenu in panel.

**Comment by fossfreedom** [comment]
Sounds like at that position in the code it should look at that menu variable and hide the menu if true  in the same way as csd  hides the menu. Seems like  a simple PR if someone wants to have a go.

**Comment by IKRadulov** [comment]
I will try to do it.When I have time.

**Comment by IKRadulov** [comment]
Ok . I found that the Appmenu in Header bar is set to Menu containing only "Quit" "About"  and "Help" Items . In order for the global menu plugins to display the rhythmbox "shared menu" the code that removes the "Help" "Quit" "About" should be removed , also the appmenu should be set to the "shared menu" . So a separate button is not needed and only the "shared menu" . What is your oppinion on this ? If you aprove it I will submit a pull request.

**Comment by fossfreedom** [comment]
Any ideas what is in the shared menu? Sounds reasonable. Happy to see the PR

**Comment by IKRadulov** [comment]
I have Mistacen the name ( Have to learn to read more carefully ) . The "shared menu" is the appmenu you import from rhythmbox at line https://github.com/fossfreedom/alternative-toolbar/blob/e2ddd1fc06631ffc090f5ba4cb6e79aa137553ab/alttoolbar_type.py#L1561 .

**Comment by fossfreedom** [comment]
K. That will break the menu appearing where it should for gnome apps in the csd button on the right hand side.
Question. If you use the compact view in the plugin settings does global menu work?

**Comment by IKRadulov** [comment]
Well according to https://wiki.gnome.org/Design/OS/AppMenu everything from rhythmbox appmenu except add music menu item should be located there . Nope the appmenu is not set in the other layouts so it does not import them.

**Comment by fossfreedom** [comment]
Happy to see any pull requests.  As long as gnome-shell's top-bar menubar isn't broken then I'm content.

**Comment by khurshid-alam** [comment]
Works fine with indicator-appmenu in unity. In unity gtk-shell-show-menu-bar & gtk-shell-show-appmenu both are true.
