### ISSUE TITLE
cd ripping controls missing

### ISSUE THREAD

**Issue by rippetoej** [fossfreedom/alternative-toolbar#118]
CD ripping controls are missing when alternative-toolbar is active. Screenshots included below. 

Ubuntu 17.04 - 64bit
Cinnamon 3.4.6
Rhythmbox 3.4.1
toolbar version 0.17.5-1 installed from the PPA.  Version 0.17.3 installed from the ubuntu repo also had the same problem.

![default](https://user-images.githubusercontent.com/4031719/34852493-f71633aa-f6fc-11e7-9cac-c6bc54f6a709.png)
![broken](https://user-images.githubusercontent.com/4031719/34852494-f7219966-f6fc-11e7-91c1-5bd15eb45634.png)

**Comment by fossfreedom** [comment]
via the appmenu enable the source toolbar or press CTRL+T to toggle the toolbar on and off

**Comment by rippetoej** [comment]
Ahh, that did it. Thank you!
