### ISSUE TITLE
Borders and padding

### ISSUE THREAD

**Issue by satya164** [fossfreedom/alternative-toolbar#12]
Some points,
* The play buttons in the bottom bar need more horizontal padding
* The bottom bar needs a border at the top
* The songs list needs to have no borders and should have no margin
* The sidebar will need a right border after that

**Comment by fossfreedom** [comment]
I've added a GtkFrame for the playbar.

With regards to the songs list - are you using Rhythmbox 3.2 or Rhythmbox 3.1?  If the former you'll see the styling has changed to have flatter less bordered windows.

With regards to the sidebar - we may or may not have a sidebar in the future.

As to the playbuttons - feel free to have a play around with the padding values - the file is alttoolbar.ui in the ui sub-folder.  Let me know what you think works best.

**Comment by satya164** [comment]
Well try.

**Comment by me4oslav** [comment]
I toyed a bit and added some padding.
Input, anyone?
![screenshot from 2015-04-03 12 24 46](https://cloud.githubusercontent.com/assets/1658870/6980562/82d221d6-d9fc-11e4-9c57-0eaac417f963.png)

**Comment by satya164** [comment]
Cool!

**Comment by me4oslav** [comment]
@fossfreedom How do I submit a merge request? Or do you just want me to tell you what I've done so you can redo it?

**Comment by fossfreedom** [comment]
just added you as a collaborator - you should now be able to check-in changes

**Comment by me4oslav** [comment]
I will push in the morning.

**Comment by me4oslav** [comment]
This commit fixes the issue:
https://github.com/fossfreedom/alternative-toolbar/commit/77de760c2829d22e703989932b3e82ffb540fd06
Here is how it looks:
![screenshot from 2015-04-04 15 11 55](https://cloud.githubusercontent.com/assets/1658870/6992519/1ce611f2-dadd-11e4-8c61-6febe23504dd.png)

**Comment by fossfreedom** [comment]
That looks much nicer.  Thanks for that.  

The volume-control button is now smaller though.  Intentional?

**Comment by satya164** [comment]
Instead of adding a frame around the bar, which adds a border on all sides, we just need border at the top.

**Comment by me4oslav** [comment]
I did not touch volume. O.o

**Comment by fossfreedom** [comment]
@satya164 - better now?

**Comment by satya164** [comment]
@fossfreedom screenshot?

**Comment by me4oslav** [comment]
@satya164 -
![screenshot from 2015-04-05 10 08 10](https://cloud.githubusercontent.com/assets/1658870/6996110/b41e5964-db7b-11e4-8ebf-e63833fd8977.png)
