### ISSUE TITLE
Is it possible to use this with Flatpak? If yes, what are the instructions?

### ISSUE THREAD

**Issue by Saroufim** [fossfreedom/alternative-toolbar#122]
A flatpaked version of Rhythmbox doesn't seem to be compatible with alternative-toolbar. Is it possible to somehow locally modify Rhythmbox to include this?

**Comment by fossfreedom** [comment]
Sorry - I have no idea how flatpak's apps work with third-party plugins.  I would suggest raising this matter on the flatpak forum - wherever that is.

maybe this? https://github.com/flatpak/flatpak

**Comment by Saroufim** [comment]
After taking the issue up with the flatpak developers, Tingping suggested this method should be followed: https://tingping.github.io/2018/03/18/flatpaking-plugins.html
By creating another package as an addon for the first.

**Comment by fossfreedom** [comment]
Thanks for the info. I'm sure that is very useful for everyone if they want plugins to work with this container format
