### ISSUE TITLE
Anyway to remove the song/artist info in the alt toolbar?

### ISSUE THREAD

**Issue by vaskark** [fossfreedom/alternative-toolbar#123]
Basically, the title. I'm wondering if I compile the plugin myself if there's any way to remove this info from the toolbar. The two lines look out-of-sorts with the overall sleekness.

Thanks.

**Comment by fossfreedom** [comment]
In the preferences for the plugin you can tick the inline song artist checkbox

**Comment by vaskark** [comment]
Thanks for responding. I tried found that feature shortly after posting. But all it does is change two lines into one line (or vice versa). I kinda wanted to not show that info there at all. If I'm stuck I can live with it :)

**Comment by fossfreedom** [comment]
ok - https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_type.py

function starting line no 949 and function starting line no 1049 - you can see how the song/artist label is being calculated.  So you can change that bit of the code if you wish.
