### ISSUE TITLE
where is it?

### ISSUE THREAD

**Issue by caltrop-3** [fossfreedom/alternative-toolbar#124]
installed and I don't see it
using rhythmbox 3.3

**Comment by fossfreedom** [comment]
You have to use rhythmbox plugins to enable it.

**Comment by caltrop-3** [comment]
Like I said - it is NOT in the plugins.Maybe a complete system restart...
Whatever, I installed Clementine, much nicer audio player.


    On Wednesday, August 1, 2018, 1:27:11 PM EDT, David Mohammed <notifications@github.com> wrote:  
 
 
You have to use rhythmbox plugins to enable it.
