### ISSUE TITLE
plugin crashes virgin Rhythmbox setup

### ISSUE THREAD

**Issue by Yeru-314** [fossfreedom/alternative-toolbar#125]
Dear all,
last week, I moved all my stuff from a machine running Ubuntu 16.04 LTS to a new device, set up with a clean slate installation of the latest point release of Ubuntu 18.04 LTS.
Alternative toolbar is preinstalled in `/usr/share/rhythmbox/plugins/alternative-toolbar`

Rhythmbox crashed every time in <10s.
The log file can be found [here](https://gitlab.gnome.org/GNOME/rhythmbox/uploads/66c038ea97cbc8eef5e17a0fbf019b58/rb_debug.log)
I reported the behaviour [here](https://gitlab.gnome.org/GNOME/rhythmbox/issues/1650).

After
`sudo mv /usr/share/rhythmbox/plugins/alternative-toolbar /usr/share/rhythmbox/plugins/alternative-toolbar-test`
it runs stable.

Any idea why?

**Comment by fossfreedom** [comment]
closing since unreproducible with no feedback as requested
