### ISSUE TITLE
Time slider is laggy/inaccurate

### ISSUE THREAD

**Issue by ugtar** [fossfreedom/alternative-toolbar#126]
While the alternative-toolbar plugin is enabled the time slider is really laggy and innacurate.  It jumps by large amounts, does not drag smoothly and often jumps either left or right when released after dragging.  This is especially pronounced when the time slider has higher granularity (eg, listening to a long track like a podcast).  When the plugin is disabled the time slider drags much more smoothly.

Using rhythmbox 3.4.2 in ubuntu 18.04.1 with alternative toolbar plugin 0.18.0
rhythmbox-plugin-alternative-toolbar/bionic,bionic,now 0.18.0-1 all [installed,automatic]

Please let me know if i can provide any more info or logs.

**Comment by fossfreedom** [comment]
Thanks for the report. 

Needs debugging. Pull-requests are welcome.

**Comment by fossfreedom** [comment]
https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_type.py line 744 self.song_progress.connect('control', self._sh_progress_control) i.e. song_progress is just above that method that is created depending upon the type of slider widget being shown (alttoolbar_widget)

If you look at the widgets themselves in altttoolbar_widget the actual connection events (button_press, button_release motion_notify) for mouse movement and slider connections are made - the "control" signal is emitted by the slider widget and the self_sh_progress_control then translates this back to control what rhythmbox needs todo.

**Comment by fossfreedom** [comment]
Resolved in git master.
