### ISSUE TITLE
Search bar shortcut

### ISSUE THREAD

**Issue by Michszcz** [fossfreedom/alternative-toolbar#130]
Could you make search bar pop up when type? Like in nautilus. And hide by pressing esc?
(really sorry for my english)

**Comment by fossfreedom** [comment]
Interesting idea. Happy to receive a pull request to implement this.

**Comment by McSinyx** [comment]
I'd be grateful if searching can be triggered by keyboard shortcut too.

**Comment by fossfreedom** [comment]
@McSinyx again - happy to receive a PR - https://github.com/fossfreedom/alternative-toolbar/issues/98 <-- that used to work but recent GTK+ changes broke the functionality as currently implemented.

**Comment by McSinyx** [comment]
I'll try to investigate on that this weekend :smile: The need of using mouse to search has been irritating me for quite a while but I'm quite busy adapting to my new study schedules.
