### ISSUE TITLE
Not working at all, no preferences, no change in the toolbar.

### ISSUE THREAD

**Issue by rolandixor** [fossfreedom/alternative-toolbar#133]
I'm on Ubuntu 18.04, using the PPA version. The toolbar isn't working. Also, the preferences don't show up.

**Comment by rolandixor** [comment]
Apparently - this is only if I start it using the .desktop file. Starting from the commandline, it works just fine.

**Comment by fossfreedom** [comment]
The plugin doesn't appear in rhythmbox's plugin preferences menu option? Note preferences and plugin preferences are two separate menu optins

**Comment by fossfreedom** [comment]
no feedback - closing.
