### ISSUE TITLE
Alternative-toolbar doesn't work on xfce - shows the xfce title bar

### ISSUE THREAD

**Issue by barrel0luck** [fossfreedom/alternative-toolbar#134]
Other apps like Nautilus, GNOME Software work fine - don't have the extra title bar along with the CSD title bar, but Rhythmbox seems to have an extra Xfce style title bar even with this plugin enabled.

**Comment by fossfreedom** [comment]
Sorry - I don't have an XFCE install to test against.

I'm guessing that CSD apps look out of place in XFCE?  Maybe switching of the CSD and using the standard or compact toolbar will be a better fit via plugin preferences

**Comment by barrel0luck** [comment]
No worries.
All the other Gnome CSD apps are catching up such that they look good even on XFCE. They don't have an extra title bar on top of the header bar. Eg. Gnome Software, Nautilus, Recipes, and others.

**Comment by fossfreedom** [comment]
For anyone using XFCE - happy to receive a pull-request to resolve.

**Comment by fossfreedom** [comment]
Tested on Ubuntu 19.10 with xfce4-session and xfce4-panel  - all looks ok.  So I can only assume things have moved on since this issue was raised.

![image](https://user-images.githubusercontent.com/996240/66268264-95759d00-e833-11e9-8ad5-a22de3c8df1a.png)

Closing.
