### ISSUE TITLE
Use GTKScale when using inline song/artist label

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#14]
from #4 - consider using the standard GTKScale instead of the custom scrobble bar when using inline-label option

**Comment by me4oslav** [comment]
This can be implemented like this - if the "inline song and artists labels" is enabled -> display the gtkscale, if the above is disabled display the current slider.

**Comment by fossfreedom** [comment]
ok - it now defaults to the GtkScale version - you can switch between the two types of progressbar (GtkScale vs Compact) via preferences.

Let me know what you think.

**Comment by fossfreedom** [comment]
Note - adwaita GtkScale is too large (height wise) for the song-artist being displayed above the progress-bar.  

Under Ubuntu Ambiance - the GtkScale actually fits nicely - so the GtkScale as I thought is very theme dependent.  I've left it to the user to choose what works best for them.

**Comment by me4oslav** [comment]
I think that these screenshots look sexy. :P
![screenshot from 2015-04-05 13 06 31](https://cloud.githubusercontent.com/assets/1658870/6996513/dd354e34-db94-11e4-8990-c52f4212b967.png)
![screenshot from 2015-04-05 13 07 55](https://cloud.githubusercontent.com/assets/1658870/6996514/dd358764-db94-11e4-97f8-4ebb951ab3de.png)
Should we close the issue now?

**Comment by fossfreedom** [comment]
yep - close.

I'm struggling with the sizing of the volume control to match the new padding.  Any ideas?

**Comment by fossfreedom** [comment]
BTW - is that two different themes you are using for those pictures?

**Comment by me4oslav** [comment]
Padding wise what I did in Glade was 1, 1 ; 5, 5 for the pause_button_image. I guess do the same for volume?
Yes - Ozon and Adwaita.

**Comment by me4oslav** [comment]
I couldn't find the volume control button in Glade. If I could I would have added padding to it too. :)
