### ISSUE TITLE
menubar for classic interface

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#145]
Rhythmbox lost its menubar a long time ago. Ubuntu are no longer distro-patchings its menubar

Wondering if there is any interest in adding the menubar back into the classic look toolbar?

http://launchpadlibrarian.net/430489371/rhythmbox_3.4.3-1ubuntu1_3.4.3-2ubuntu1.diff.gz

Implementation is straightforward - just nick the .ui file from that diff - then add the menu in a similar way.

Should be simple if anyone is interested in implementing it.

**Comment by ThePillenwerfer** [comment]
I simply wanted to say Thank You Very Much for this.
