### ISSUE TITLE
Add repeat once capability

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#15]
coming out of #4 and other discussions, consider adding a repeat once function.

The method discussed in #4 to add an always on down arrow just doesnt work for me so not going to implement an always visible method.

Maybe consider looking at displaying a much narrower version of the drop-down when hovering over the repeat button - something like windows media player.

**Comment by me4oslav** [comment]
The Gnome HIG approved solution is like this:
![screenshot from 2015-04-04 16 06 05](https://cloud.githubusercontent.com/assets/1658870/6992734/851c45e6-dae4-11e4-9376-960b9e6612fc.png)
Clicking on the arrow will open a menu with the repeat options.
This would mean that the repeat and shuffle buttons will have to be separated.

**Comment by me4oslav** [comment]
Any decision about this one? Because the sooner the remaining issues with alternative-toolbar are gone, the better.

**Comment by fossfreedom** [comment]
Repeat-once is not a core rhythmbox function - it needs code to be developed to support this function.

There is another plugin called repeat once.  Myself (or someone else) will need to have a look at what is the best way to incorporate this plugin so that we dont start having to have a proliferation of additional add-ins.

Thus, the arrow issue is just the minor part of this.

**Comment by HEXcube** [comment]
What about clicking the *repeat all songs* button twice to make it *repeat one song*? I've seen it on many music players, especially those on mobile devices. This should give you an idea, though the mockup is terrible :-)
Button in default mode (Repeat All Songs):
![without repeat](https://cloud.githubusercontent.com/assets/3755396/7511324/abb40b98-f4c1-11e4-9382-4c45f2d322c9.png)
When clicked again it should change into this:
![repeat one song](https://cloud.githubusercontent.com/assets/3755396/7511340/cb63e062-f4c1-11e4-8c81-f25d2748aa34.png)
@fossfreedom Or can you make the [Repeat One Song plugin](https://launchpad.net/repeat-one-song) display icon on toolbar, like it did on Rhythmbox 2.xx?

**Comment by fossfreedom** [comment]
@HEXcube 

  thanks for your thoughts.

This would be ok if the repeat button was a standard button - it currently is a toggle button like the shuffle button - so being depressed show the repeat is in action - toggle off, repeat is not in action.

I dont like the idea of a second button.

My current thought is centering around using a Gtk Popover.

1. clicking repeat button will display the popover showing two icons side-by-side - one with the repeat all button (depressed), the other repeat once (not depressed)
2. moving the mouse within the popover allows you to choose the repeat mode you want. Clicking the mode in the popover changes the icon in the button
3. moving the mouse out of the repeat button boundary hides the popover.  likewise moving the mouse outside of the popover boundary hides the popover.
4. if the repeat button is depressed and you move the mouse within the repeat button boundaries - the popover reappears allowing you to choose the repeat mode
5. toggling off the repeat button hides the popover

The above would work for GTK3.12 and above users (Ubuntu Utopic and vivid) but not for Ubuntu Trusty users.  So not sure what to-do for these users.

**Comment by me4oslav** [comment]
I will have launch and read the discussion.

**Comment by me4oslav** [comment]
The popover solution is not a bad idea. I like it.
But like David himself outlined, it will not work for the Ubuntu LTS, which could prove itself problematic.
It is either that or the Gnome HIG solution. The latter will work on any GTK 3x, but its issues is that it wastes a bit of X space.

**Comment by fossfreedom** [comment]
ok - have now got some working code for this issue.

Only tested on ubuntu vivid at the moment.

Still to do:

1. test and fix any issues on Ubuntu trusty
2. sort out the tooltips on the popover (they are missing).

Note - the current tooltip for the repeat button is actually wrong ("Repeat the current track") since it repeats all tracks in the view/playlist etc.  I've reused this tooltip for the repeat-one-song capability.  The new default string is "Repeat all tracks" - this unfortunately requires an additional translation string.

**Comment by me4oslav** [comment]
Will test, outline issues and if possible fix papercuts too.

**Comment by me4oslav** [comment]
Ok, here are issues:
  -  The repeat and shuffle button now must get two separate buttons, because of the popover; It is repeat button specific, not repeat and shuffle specific;
  -  add tooltips in popover mode;
  -  the bugs you outlined;
One question - will there be a preference for that? 'Cause at least it this case, I don't see a point - if the user does not what repeat once capability (s)he will just ignore it in the popover.

**Comment by fossfreedom** [comment]
Don't really follow the request for a preference.  I think most people will instantly recognise "repeat one" functionality - its common on most media players ... just not in rhythmbox until now!

Anyway - have split the buttons - 3px space between them ... and 3px for the volume control if that is also visible.

Tooltips in popover if the tooltip option is switched on in preferences.

BTW - 18 languages and locales is quite amazing.  Very pleased personally that so many translators have invested their time in this project :)

**Comment by me4oslav** [comment]
Shall test and comment in the morning.

**Comment by me4oslav** [comment]
Shouldn't the spacing be 5px?
Apart from that - it seems fine.
The preferences request was about not adding a preference to do disable the ability to switch between repeat modes. The way I see it is that if the user does not want repeat once capability (s)he won't use it.

**Comment by fossfreedom** [comment]
thanks for the 5px change.

The repeat functionality is not an oft invoked capability nor "in your face" like a tooltip.  Thus not convinced a preference option here will be necessary.  If there was a clamour for this then will re-evaluate.

**Comment by me4oslav** [comment]
Excellent, so we both agree that a preference is not needed. :)
I will try to find some time for coverart design work too.

**Comment by HEXcube** [comment]
Tested the plugin from *repeat-one-song* branch (now merged to *master*) on **Ubuntu 14.04LTS _"Trusty"_** and I'm happy to say that it works fine.

- **Unpressed** (Default mode)
![unpressed - default mode](https://cloud.githubusercontent.com/assets/3755396/7770365/4b7b4282-00ab-11e5-9552-97ea3604c5e7.png)

- **Pressed** (Popover shows Repeat options)
![pressed - popover shows repeat options](https://cloud.githubusercontent.com/assets/3755396/7770465/4bfeee88-00ac-11e5-8b40-fbf1ee7c09ef.png)

- **Repeat One Song** mode
![repeat one song mode](https://cloud.githubusercontent.com/assets/3755396/7770474/636f3636-00ac-11e5-9fee-2e9c78ffbf77.png)

*Repeat One Song* was one of the features I missed the most when Rhythmbox moved from v2.9x to v3.x series. Though the plugin was still usable, it could no longer add *repeat-one-song* icon to Rhythmbox 3.x's static toolbar. @fossfreedom n' @me4oslav Thank u guys, for bringing this much needed feature back, with a better implementation! :-)

**Comment by fossfreedom** [comment]
@HEXcube 

  excellent.  Many thanks for testing this.

I'll be uploading the new version into my PPA in the next few days - I want to include most of the updated translations that are being worked on by the launchpad translation community.

**Comment by me4oslav** [comment]
BTW, David - if you wanna supply the community with bleeding edge builds it may be worth doing a daily PPA.
But I am not sure it is worth it.

**Comment by fossfreedom** [comment]
that's an interesting idea - I've meaning to investigate launchpad's autobuild facility.  Might do this for coverart-browser.

**Comment by me4oslav** [comment]
I think @satya164 can teach you.

**Comment by me4oslav** [comment]
Or maybe @paolorotolo.
