### ISSUE TITLE
Can you make the keybinder depends optional

### ISSUE THREAD

**Issue by seb128** [fossfreedom/alternative-toolbar#150]
The depends was added in commit #d32b5238 but from the commit it's not really clear what was the problem with using GDK events to handle ctrl-F.

In any case keybinder is in universe for Ubuntu and it's blocking the update for us. We could add it to our set but it's not clear that it's useful enough at this point for us to take on maintaining an extra component.

Could you make it optional (or maybe explain why the depends is needed/what can't be done with gtk alone there?).

**Comment by fossfreedom** [comment]
Rhythmbox seems to swallow the CTRL+F events within various widgets - i.e. doesnt pass the event up the stack. So much so it doesnt appear to be trappable via the application window.

Sure - easy enough to make the keybinding import option.

**Comment by seb128** [comment]
Could it be fixed in rhythmbox? Probably some return value to change in event handlers to tell widgets to not eat the keybinding?

**Comment by fossfreedom** [comment]
Well anything is possible.  I'll look at rhythmbox in (very) slow time - but have several UB priorities that have to take priority.

**Comment by seb128** [comment]
Ok, that makes sense, I will probably revert patch that change in Ubuntu for now to unblock the update and I will have a look to keybinder to see how trivial it is/if that would be fine to add to our list of things we are ready to maintain in main for Ubuntu

**Comment by fossfreedom** [comment]
Before you do that - give me a few days to-do the optional stuff etc -
I'll upload to debian and the revised version will then sync

**Comment by seb128** [comment]
Will do, thx!
