### ISSUE TITLE
Control+F hijacked from other applications

### ISSUE THREAD

**Issue by ranolfi** [fossfreedom/alternative-toolbar#151]
Did a clean install and enabled the plugin.

Looks neat and well done (congratulations), however I'm experiencing a terrible problem. When Rhythmbox is open, it prevents me from using the <kbd>Ctrl</kbd>+<kbd>F</kbd> keyboard shortcut in other applications! Like Firefox, Gedit or Chromium. This, obviously, happens when the Rhythmbox window is not active or in focus, hence the "hijack". (Took me a while to figure out what was happening).

Interestingly enough, this does _not_ happen with any of the other [keyboard shortcuts](https://github.com/fossfreedom/alternative-toolbar#keyboard-shortcuts) from this plugin - just <kbd>Ctrl</kbd>+<kbd>F</kbd>.

For reference, I'm using Cinnamon 4.4.8 with the default theme on Arch Linux. Software package from [AUR](https://aur.archlinux.org/packages/rhythmbox-plugin-alternative-toolbar-git/), build @ current master HEAD (f53c316).

**Comment by fossfreedom** [comment]
Hmmm.... interesting side effect of using  gir1.2-keybinder-3.0 to detect
ctrl+f

That will need investigating

**Comment by fossfreedom** [comment]
okey dokey - this could be done I guess by listening for the application window focus event - if it gets focus - set the keybinding, if it loses focus then unbind the keybinding

https://github.com/fossfreedom/alternative-toolbar/commit/d32b5238e079d12b36bb4bfac4ccab3239a87948#diff-7eaa5a1e578ec5825df16dca1443ff99R1386

https://lazka.github.io/pgi-docs/Keybinder-3.0/functions.html

If this doesnt work then lets drop the use of keybinder completely.

**Comment by ranolfi** [comment]
Should work, but kind of a hack, as Keybinder is specifically for "for registering global keyboard shortcuts". Of course the Ctrl+F shortcut in an application need *not* be global, so...

I don't suppose `ActionGroup.add_action(...)` (as done in https://github.com/fossfreedom/alternative-toolbar/blob/master/alternative-toolbar.py#L264) could work in this case so as to do away with Keybinder?

**Comment by fossfreedom** [comment]
Ok - do you want to get the above change a good test please?

**Comment by ranolfi** [comment]
Will do. I even tried implementing it myself but, being entirely unfamiliar with GTK, didn't manage to get it working.

Let you know soon.

**Comment by ranolfi** [comment]
Nice, it works - but not exactly like the previous implementation.

This one toggles the search bar on, but does not hide it after pressing the shortcut again.

Is that easy to deal with?

**Comment by fossfreedom** [comment]
Pressing escape will close the search-bar.

**Comment by ranolfi** [comment]
Confirmed!

Thanks
