### ISSUE TITLE
[Idea] Waveform seekbar

### ISSUE THREAD

**Issue by XanderLeaDaren** [fossfreedom/alternative-toolbar#152]
Thank you everyone for the work done to ingreater even better Rhythmbox within Gnome.

As a question, how difficult would it be to feature a waveform seekbar, similar to the one to be found in other softwares, like e.g. in Quod Libet ?

![68747470733a2f2f6c617a6b612e6769746875622e696f2f5f696d616765732f323031372d30332d30315f31392e34302e34372d3833373032343834303937363633333836342d312e6a7067](https://user-images.githubusercontent.com/28948599/84872567-58c89980-b082-11ea-936d-04d3d49975f3.jpg)

**Comment by fossfreedom** [comment]
Should be fairly straightforward if you take the ideas behind

https://github.com/fossfreedom/rhythmbox-spectrum

If you look at the code there it takes the gstreamer data and creates a graph.  So - a bit of manipulation and you could create a waveform like idea.

This issue isnt in scope for this plugin so I'll close it here.  Hopefully the above will inspire  you.  Good luck!
