### ISSUE TITLE
Disabling alt-toolbar plugin doesn't reset UI fully

### ISSUE THREAD

**Issue by crvisqr** [fossfreedom/alternative-toolbar#154]
Rhythmbox version: 3.4.4

Refer screenshot:

![Screenshot from 2020-08-07 21-21-52](https://user-images.githubusercontent.com/59721464/89664082-3cafde80-d8f4-11ea-9099-74024d1c3718.png)

The side pane is empty, and there are duplicate controls at the bottom.

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**Comment by fossfreedom** [comment]
It's really difficult todo a reset after disabling given the extent of the changes needed to make the plugin work effectively. Hence just better to restart.

I have no intention in spending any time  on this issue when a restart will suffice.

**Comment by crvisqr** [comment]
Okay.

But how is the user expected to know that Rhythmbox should be restarted when disabling the plugin ?

**Comment by fossfreedom** [comment]
Obviously it doesn't look 100% so people will restart.

As I said, I am not prepared to spend the considerable amount of time to
resolve.   That doesn't stop anyone resolving and doing a pull request.
