### ISSUE TITLE
Cannot add music

### ISSUE THREAD

**Issue by crvigh** [fossfreedom/alternative-toolbar#158]
Please refer:

https://bugs.launchpad.net/ubuntu/+source/rhythmbox/+bug/1893113

**Comment by fossfreedom** [comment]
Immediate thoughts is that there has been a label change for the source toolbar

https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_controller.py#L323

Need to check if it's slightly different from the "Import" label in rhythm box v3.4.4
