### ISSUE TITLE
Statusbar with datasize, number of tracks and playtime invisible on Rhythmbox 3.4.4 / Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by hedgecrog** [fossfreedom/alternative-toolbar#159]
Rhythmbox 3.4.4 seems to have removed the old statusbar, at least running with default desktop on Ubuntu 20.04 (option is greyed out under View in the menu bar when alternative-toolbar is disabled). However, the information usually visible in the statusbar (filesize, number of tracks, playtime) is still visible in a small view/window at the bottom of rhythmbox (WITH ALTERNATIVE-TOOLBAR DISABLED), see screenshot 1 below.

HOWEVER, with alternative-toolbar activated, this view is completely invisible. I've tried setting all different settings in alternative-toolbar and rebooting rhythmbox inbetween every setting toggled. I guess this is a bug with alternative-toolbar (also see forum posts on https://forums.linuxmint.com/viewtopic.php?t=324562 and https://www.reddit.com/r/linuxmint/comments/htklha/rhythmbox_statusbar/ which probably is an effect of the same bug ). 

Only way at the moment to see filesize, number of tracks and playtime of the music library, or different playlists on Ubuntu 20.04 atm is to temporarily disable alternative-toolbar, reboot Rhythmbox, see the info, activate alternative-toolbar and reboot rhythmbox again.

best regards,
![Skärmavbild 2020-09-09 kl  22 16 20](https://user-images.githubusercontent.com/1503926/92648906-7ce6f000-f2ea-11ea-80d6-a9e346f7eff0.png)

![Skärmavbild 2020-09-09 kl  22 15 15](https://user-images.githubusercontent.com/1503926/92648926-84a69480-f2ea-11ea-8cfb-4afcd4367883.png)

**Comment by fossfreedom** [comment]
I've hidden that deliberately - its just such bad UX and breaks the look and feel of the app with the toolbar.
I would prefer to readd the old statusbar but as you say its been removed from the source.

**Comment by hedgecrog** [comment]
ok I see. But could you at least make it possible to have it visible with alternative-toolbar activated with a setting in alternative-toolbar?

**Comment by fossfreedom** [comment]
not really - its just a gastly construct that I don't want anything to be
associated with.

My preferred solution would be to grab that info and present it in another
way.

The how-to-do is the question which I don't have an answer for.
