### ISSUE TITLE
add a pause-stop capability 

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#16]
from discussion in #4 consider adding a pause - stop function instead of the current pause button function.

like #15 - should be implemented in a consistent method with repeat once for whatever method is chosen.

**Comment by me4oslav** [comment]
Check this comment for HIG solution:
https://github.com/fossfreedom/alternative-toolbar/issues/15#issuecomment-89574803
Except in this case we should not separate the <prev | play/pause/stop | next> button.

**Comment by fossfreedom** [comment]
ok - looking at this further.  Rhythmbox makes a very definitive decision itself whether to use "pause" for a playing source vs "stop" for others.  

In Gstreamer terms - stop releases all resources including losing track of the current playing source.  Thus forcing a stop on a playing source that wasnt expecting this will probably cause more unexpected issues for playing future tracks on a "forced stopped" source

This report is not a good idea to be implemented - so closing for the above reasoning.
