### ISSUE TITLE
Feature request: Remove this button

### ISSUE THREAD

**Issue by SeaDve** [fossfreedom/alternative-toolbar#163]
![image](https://user-images.githubusercontent.com/64297935/103856290-59dd1900-50ef-11eb-90f5-453ac807d7fa.png)
I think this button don't have any use other than showing a single edit button. Maybe remove it and directly open this drop-down instead from the same button in the header bar. 
![image](https://user-images.githubusercontent.com/64297935/103856413-90b32f00-50ef-11eb-8f14-faf36b11039d.png)

**Comment by fossfreedom** [comment]
that's basically the same as #71
