### ISSUE TITLE
Global menu with controls at the bottom

### ISSUE THREAD

**Issue by helfper** [fossfreedom/alternative-toolbar#166]
I like the controls at the bottom from the modern style, but as a Unity user I'd prefer to have a global menu, instead of a hamburger menu, which only exists in the compact style.

Currently, there are 3 styles to control (depending on how you count) 4 UI features:

  | Standard | Compact | Modern | Wanted
-- | -- | -- | -- | --
Controls Location | Top | Top | Bottom | Bottom
Controls Style | Standard | Compact | Compact | Compact
Menu Bar/Global Menu | No | Yes | No | Yes
Songs/Categories Header Bar | No | No | Yes | No

My suggestion would be to add a new setting to control the "Menu Bar/Global Menu" independently of the current double setting Modern/Use compact controls. Ideally, I'd prefer to not have a header bar at all, but I can live with that.

**Comment by fossfreedom** [comment]
Seems reasonable.

Nice mini project for anyone to have a go at.
