### ISSUE TITLE
Bind Ctrl+F to showing and focusing the search toolbar when it is not already shown

### ISSUE THREAD

**Issue by nekohayo** [fossfreedom/alternative-toolbar#167]
Ctrl+F should:
* Focus the search toolbar's field if the toolbar is already shown but not focused (currently implemented behavior, which is correct, keep it)
* Show/activate the search toolbar when it is _not_ already shown (and focus the search field) - this is the missing behavior.

**Comment by nekohayo** [comment]
I will also add that this is the plugin version packaged in Fedora, 0.18.4; I see now that there were half a dozen bugs about this, but it seems none recently?

**Comment by fossfreedom** [comment]
Please uplift to the latest version since this area has been reworked since 0.18.4
