### ISSUE TITLE
Closing the search bar with Escape keyboard shortcut confuses the toggled state

### ISSUE THREAD

**Issue by nekohayo** [fossfreedom/alternative-toolbar#168]
With version 0.18.4, the Esc key, when focus is in the search toolbar's entry, should clear the search and dismiss the search toolbar; it does that, however the search togglebutton is still toggled, so when you try to reopen the search toolbar by clicking that button (until you can do so with Ctrl+F as per #167), the toolbar opens and immediately closes.

**Comment by fossfreedom** [comment]
Please uplift to the latest version since this area has been reworked since 0.18.4
