### ISSUE TITLE
Columns cannot be moved

### ISSUE THREAD

**Issue by leoniscsem** [fossfreedom/alternative-toolbar#169]
Ubuntu 20.04
GNOME 3.36.4
Rhythmbox 3.4.4
alternative-toolbar 0.19.3

After activating the plugin on a fresh install, trying to drag and drop columns does not show any results.

**Comment by fossfreedom** [comment]
Column moving is disabled on non English locales due to a weird Gtk bug

https://github.com/fossfreedom/alternative-toolbar/issues/138
