### ISSUE TITLE
Inaccuracy in README - wrong package name for Fedora

### ISSUE THREAD

**Issue by maxborowsky** [fossfreedom/alternative-toolbar#175]
Fedora does not require a non-existent **pkg-config** package, but a **pkgconfig** (and, maybe, **pkgconf-pkg-config**). See https://fedoraproject.org/wiki/Changes/pkgconf_as_system_pkg-config_implementation

**Comment by fossfreedom** [comment]
Please make a pull request with the necessary corrections. Thx.

**Comment by maxborowsky** [comment]
@fossfreedom, unfortunately, I don't have enough experience with Github to do what you're asking for :-(
