### ISSUE TITLE
Missing file in tar.xz archive

### ISSUE THREAD

**Issue by maxborowsky** [fossfreedom/alternative-toolbar#176]
In the README part about source compilation for Fedora, it is written that I should use the command

`./autogen.sh --prefix=/usr`

But the **autogen.sh** file in the **alternative-toolbar-0.20.2.tar.xz** archive is missing.

Or I have to download the _Source code archive_ (tar.gz)?

**Comment by fossfreedom** [comment]
Revised the instructions to install from the release file

https://github.com/fossfreedom/alternative-toolbar/commit/6cac11564f31fdf00b367a7956f79e1a59682170
