### ISSUE TITLE
Enhanced plugin dialog not working

### ISSUE THREAD

**Issue by TylerMS887** [fossfreedom/alternative-toolbar#178]
The enhanced plugin dialog does not seem to be working:

![image](https://user-images.githubusercontent.com/115214762/203143295-59ef79c5-2e81-41ea-9a4f-23409378a51c.png)

I can confirm it is enabled:

![image](https://user-images.githubusercontent.com/115214762/203143368-4369c66b-5f0f-493e-a3b3-44d866ee4f97.png)

**Comment by fossfreedom** [comment]
Thx for the report.

Yeah, that option was only applicable in older versions of rhythmbox. It needs to be removed as an option now.
