### ISSUE TITLE
Alternative Toolbar Removes Status Bar & Disables It In View Menu

### ISSUE THREAD

**Issue by UbuntuMetal** [fossfreedom/alternative-toolbar#179]
Hi. Great plugin, BUT this removes the status bar - one of the things I like about Rhythmbox, as it shows the total duration of album or playlist - and in the View menu it totally disables it. If this isn't a bug, and you don't plan to allow showing of the status while this plugin is active, do you know of a setting in a config file I can edit to get this back? I didn't realise how much I'd miss this until it was gone, so it's pretty much a deal-breaker for me. Many thanks.

Using Rhythmbox 3.4.4 with Alternative Toolbar 0.20.2 in Ubuntu 22.04

**Comment by fossfreedom** [comment]
The status bar was removed about 4 years ago by a rhythmbox change itself.
I.e. the ability to toggle it on or off

https://www.google.com/amp/s/ubuntuhandbook.org/index.php/2019/01/rhythmbox-3-4-3-released-with-numerous-bug-fixes/

**Comment by UbuntuMetal** [comment]
> status bar was removed about 4 years ago

Well, until I installed this plugin, I DID have the status bar. I've had this machine since 16.04, so maybe it retained it through the upgrades to 22.04, though that's strange, as I'm used to losing functionality as Gnome "progresses". But I assure you in 3.4.4 I had the full status bar right up until I installed this plugin. Now, if I disable Alternative Toolbar, I at least get the modern Gnome equivalent - as long as something shows me the number of songs, duration and filesize, I don't really care if it's in the form of a fixed status bar or a floating thingy.

So do you know of a way to get Rhythmbox to show this while Alternative Toolbar is enabled? Thanks.

![total](https://user-images.githubusercontent.com/41879371/210064378-5fcde902-c194-4225-9735-0c61f1e1d1fb.png)
![view](https://user-images.githubusercontent.com/41879371/210064795-d1de416a-b615-4c19-9c39-d5f2a9bdc6ad.png)

**Comment by fossfreedom** [comment]
If you are talking about the floating bar that was deliberately disabled.

You can reverse patch that if you want it back

https://github.com/fossfreedom/alternative-toolbar/issues/137

**Comment by UbuntuMetal** [comment]
Forgive my ignorance, but I'm unfamiliar with the term "reverse patch" - is this something I need to do, or do I just comment on the page you linked to ask for it back? Regarding "the opacity of the the floating-bar css" I can do that if I know which file to edit, and preferably what line. Many thanks for your time and attention on this - and the quick replies!

**Comment by UbuntuMetal** [comment]
OK, I found /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py and changed the opacity to 1, and all is good! And sorry to put you through this - I can see by your repeated use of "ghastly" that you hate this with a passion, so apologies for the trauma I've inflicted upon you by making you relive this nightmare!
