### ISSUE TITLE
Search box papercuts.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#19]
There are two issues with the search box.
A) It should be toggable with Ctrl+F;
B) When it is shown it should look like this:
![screenshot from 2015-04-05 14 06 02](https://cloud.githubusercontent.com/assets/1658870/6996662/2aa873a0-db9d-11e4-8c63-3ac68fbf939b.png)
Just a box without text, which is selected by default, so after the users has clicked search / pressed ctrl+f he will be able to start typing in it without extra mouse clicks.
Both are Gnome HIG things.

**Comment by demetrislambrou123** [comment]
can I add something about the search that it is bothering me? in nautilus when you hit the search button the gtktoolbar for search spans only on the file viewer (nautiluscanvasviewcontainer) and ignoring the favourites side pane (gtktreeview) - as shown in the first picture. In your plugin of rythmbox it spans in both the song list (gtknotebook) and the side pane (gtktreeview) - as shown in the second picture. I think it's much more visually logical to span only by the song list and ignore the side pane.
![ryhtmbox-current-search](https://cloud.githubusercontent.com/assets/3905568/6996776/cbfe10d6-dba5-11e4-8b51-32f2bc6e023d.png)
![nautilus-proper-search](https://cloud.githubusercontent.com/assets/3905568/6996775/c7a3b4e6-dba5-11e4-93e1-e7f67ae54a0e.png)

**Comment by me4oslav** [comment]
Of course you can comment, duh. :P 
Not a bad point. It all comes down to where the search searches. Does it search only through the tracklist pane or does it search through whatever search is there on the sidebar.
If former - you are correct. If latter - we keep it as it is.

**Comment by demetrislambrou123** [comment]
It is the former. If I select music from sidebar (my local library) it only search on my local library thus the track list pane. If i choose radio from sidebar then it only search the radio stations nothing else and this is the same for play lists and anything else.

**Comment by me4oslav** [comment]
So, @fossfreedom, can we get that fixed?

**Comment by fossfreedom** [comment]
@demetrislambrou123 - I think the above commit resolves this.  

Any chance you can give this a good test please.  I dont know if what I've done has any inadvertent side effects.  It seems to work with a quick look at the standard sources and external plugins such as my CoverArt Browser.

**Comment by me4oslav** [comment]
Should we close this bug when all issues outlined in it are now gone?

**Comment by fossfreedom** [comment]
yes - agreed.  I would love to get some feedback though just in-case I've not caught every scenario for this change.

**Comment by me4oslav** [comment]
Lemme test.

**Comment by me4oslav** [comment]
Everything seems to work, but the sidebar needs a border on the right, for the popping up search pane to not look out of place. Apart from that - it is fine.

**Comment by demetrislambrou123** [comment]
yeap its perfect now :) keep up the awesome work and looking forward for ozon stable release
