### ISSUE TITLE
Papercut - album art popover should go away when mouse doesn't hover the album art in the play bar.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#27]
Because it can be really irky to click somewhere in order to deactivate something that activates with hovering over an element.

**Comment by fossfreedom** [comment]
think the above commit fixes this.

**Comment by me4oslav** [comment]
Will test tomorrow morning.

**Comment by me4oslav** [comment]
It is fixed now. Closing.
