### ISSUE TITLE
no button to setting with this toolbar

### ISSUE THREAD

**Issue by Darkmagister** [fossfreedom/alternative-toolbar#28]
i'm using rhythmbox on debian, i don't have menu in the music player and as soon i enable your plugin, is just change i can not access anymore to the settings and plugin manager to change setting on this plugin and anything else, there is a shortcut to do that? o how can i fix this?

thanks

**Comment by me4oslav** [comment]
What is your desktop environment?
If it is Gnome 3, you can access the settings and plugin manager from the appmenu as shown here:
![screenshot from 2015-04-21 17 50 09](https://cloud.githubusercontent.com/assets/1658870/7254970/f518bb46-e84e-11e4-87b3-a4d5a1e4f146.png)

**Comment by Darkmagister** [comment]
i'm using enlightenment ... no app menu for me :( any way to add the preferences button to the toolbar?

**Comment by me4oslav** [comment]
I haven't heard f that desktop environment/shell at all. Sorry. :(
How does Rhythmbox look for you? Screenshot?

**Comment by Darkmagister** [comment]
here!
![rhythmbox](https://cloud.githubusercontent.com/assets/405742/7255131/af5f292a-e847-11e4-8ebd-7a1903e5961c.png)

it just have the border from my DE around ot but nothing different, i'll probably have to understand how to add another button to this plugin so i can use it!

here the website of the DE:
https://www.enlightenment.org/

**Comment by fossfreedom** [comment]
@Darkmagister - for non app menu desktops, there should be an icon on the right-hand-side of the search button - next to the close button on the screenshot above.

**Comment by fossfreedom** [comment]
ok - so you have enabled the plugin?

Please launch rhythmbox from a terminal as follows:

    rhythmbox -D alt

Please let me know what the output you see in the terminal after you enable the plugin.

**Comment by Darkmagister** [comment]
@fossfreedom i've re-installed the plugin re-enabled it, and now after i've chosen the client-side decoration and restarted it, it work bretty good !!!!
thanks!!!
![rhythmbox1](https://cloud.githubusercontent.com/assets/405742/7255342/ec0547aa-e848-11e4-90a9-9e325bcc56f5.png)

**Comment by me4oslav** [comment]
@fossfreedom Oh, seeing the latest screenshot by @Darkmagister, I gotta say that the appmenu button should be framed like all the other buttons.

**Comment by fossfreedom** [comment]
yep - it needs the button relief turned on.  Strange that's its off.  Easy fix to do.

**Comment by me4oslav** [comment]
Excellent. Should we close this bug report and open another another one about the framing papercutt?

**Comment by fossfreedom** [comment]
@Darkmagister - if you dont mind - I'll keep this open until the button relief issue is fixed.

Will let you know so that you can download the latest and confirm.

thanks again.

**Comment by me4oslav** [comment]
I kinda filed an issue for the framing - https://github.com/fossfreedom/alternative-toolbar/issues/29

**Comment by Darkmagister** [comment]
thanks to you!

**Comment by fossfreedom** [comment]
@Darkmagister - the latest commit should fix this for you.

**Comment by kingd** [comment]
I am having the same issue. Modern version works OK, but the default one has no settings icon.
I am using Debian with MATE.

![toolbar](https://cloud.githubusercontent.com/assets/6278599/10716775/2f12dffa-7b3b-11e5-9706-7a18e99fd42c.png)


Output on activation:
```
(17:03:44) [0x250cb50] [AltToolbarCompact.set_visible] alternative-toolbar/alttoolbar_type.py:1720: show_compact

(rhythmbox:13238): Gtk-CRITICAL **: gtk_box_pack: assertion 'gtk_widget_get_parent (child) == NULL' failed
(17:03:44) [0x250cb50] [AltToolbarCompact._setup_compactbar] alternative-toolbar/alttoolbar_type.py:1693: not hidden but compact
(17:03:44) [0x250cb50] [AltToolbarCompact.source_toolbar_visibility] alternative-toolbar/alttoolbar_type.py:432: source_bar_visibility
(17:03:44) [0x250cb50] [AltToolbarPlugin.on_page_change] alternative-toolbar/alternative-toolbar.py:750: page changed
(17:03:44) [0x250cb50] [AltToolbarPlugin.on_page_change] alternative-toolbar/alternative-toolbar.py:750:  
(17:03:44) [0x250cb50] [AltToolbarPlugin.on_page_change] alternative-toolbar/alternative-toolbar.py:750: <__main__.RBLibrarySource object at 0x7f949c1ebca8 (RBLibrarySource at 0x280ebf0)>
(17:03:44) [0x250cb50] [AltToolbarCompact.reset_toolbar] alternative-toolbar/alttoolbar_type.py:347: reset toolbar
(17:03:44) [0x250cb50] [AltToolbarCompact.reset_toolbar] alternative-toolbar/alttoolbar_type.py:355: found
(17:03:44) [0x250cb50] [AltToolbarCompact.post_initialise] alternative-toolbar/alttoolbar_type.py:748: True
(17:03:44) [0x250cb50] [AltToolbarCompact.post_initialise] alternative-toolbar/alttoolbar_type.py:748: True
(17:03:44) [0x250cb50] [Repeat._set_toggle_tooltip] alternative-toolbar/alttoolbar_repeat.py:180: all songs
(17:03:44) [0x250cb50] [Repeat._on_repeat_type_changed] alternative-toolbar/alttoolbar_repeat.py:211: repeat type changed
(17:03:44) [0x250cb50] [Repeat._on_repeat_type_changed] alternative-toolbar/alttoolbar_repeat.py:211:  
(17:03:44) [0x250cb50] [Repeat._on_repeat_type_changed] alternative-toolbar/alttoolbar_repeat.py:211: False
(17:03:45) [0x250cb50] [AltToolbarCompact.reset_toolbar] alternative-toolbar/alttoolbar_type.py:347: reset toolbar
(17:03:45) [0x250cb50] [AltToolbarCompact.reset_toolbar] alternative-toolbar/alttoolbar_type.py:355: found
(17:03:46) [0x250cb50] [AltToolbarSidebar._traverse_rows] alternative-toolbar/alttoolbar_sidebar.py:590: 0
(17:03:46) [0x250cb50] [AltToolbarSidebar._traverse_rows] alternative-toolbar/alttoolbar_sidebar.py:590:  
(17:03:46) [0x250cb50] [AltToolbarSidebar._traverse_rows] alternative-toolbar/alttoolbar_sidebar.py:590: <DisplayPageGroup object at 0x7f949c174870 (RBDisplayPageGroup at 0x26e3860)>
...
```

**Comment by fossfreedom** [comment]
@kingd 

  this issue was specifically about the modern header bar implementation.

Yours is about the compact view.  Can you create a new issue for this?
