### ISSUE TITLE
Phones appears with improper naming in the new sidebar.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#30]
When I plugged my Nexus 5 in the new sidebar it appears in "Other sources" category and it first says "Media player", which after a while gets changed to "Nexus 5".
Ideally it should appear in "Local collection" as "Nexus 5".

Screenshots:

![91800e06-e833-11e4-87cf-5468e219a757](https://cloud.githubusercontent.com/assets/1658870/7276968/e7275d5e-e915-11e4-8d59-f74fb4a2f282.png)
![d7d16634-e833-11e4-8de7-13f1f5d813f2](https://cloud.githubusercontent.com/assets/1658870/7276967/e7271d44-e915-11e4-955a-e2044a9a2ab8.png)

**Comment by fossfreedom** [comment]
Hi - did you try with the latest stuff I checked in last night and merged with master?

This is working for me.  Ditto with the magnatune issue.

**Comment by me4oslav** [comment]
Closed the magnatune issue for it seems fixed. The phone issue is just the name changing. It appears in the proper place, but the name is firstly "Media Player" and after a while it becomes "Nexus 5". Is that even fixable?

**Comment by fossfreedom** [comment]
The Media Player to Nexus 5 is core Rhythmbox.  It looks like rhythmbox recognises that a phone has connected so it defaults to Media Player.  Then it throws a "who are you request" at the phone (you can see this happening if you run rhythmbox in debug mode).  The phone itself takes time to respond - but when it does then the name changes.

**Comment by me4oslav** [comment]
So, not fixable. Closing this.
