### ISSUE TITLE
New sidebar doesn't start with the expanded and collapsed statuses of the sources from the player last run.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#32]
The player always starts with local collection expanded and online sources and playlists collapsed. It should remember which categories are left expanded and which collapsed on startup;

**Comment by fossfreedom** [comment]
should be fixed with the latest master code.

**Comment by me4oslav** [comment]
I will test.

**Comment by me4oslav** [comment]
Which commit fixes this?

**Comment by fossfreedom** [comment]
this one:

https://github.com/fossfreedom/alternative-toolbar/commit/bbf4f3250c4a2ea1624ad82e153712a0bdc6aefc

**Comment by me4oslav** [comment]
All right, will test in the morning.

**Comment by me4oslav** [comment]
Seems fixed. Closing.
