### ISSUE TITLE
Tooltips.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#33]
Gnome HIG is very much pro tooltips, so I guess we should add tooltips to the buttons on the header and playbar. However, the tooltips should also be meaningful, so the user will not get a toolip saying "Previous" when (s)he hovers over the previous song button.
So, here are some tooltips that I came up with:
Play - "Resume the playback"
Pause - "Pause the playback"
Stop - "Stock the playback"
Previous - "Play the previous song from the tracklist"
Next - "Play the next song from the tracklist"
Shuffle - "Play the songs in random order"
Repeat - "Repeat the current song"
Search - "Search for music in the selected view"
Now let us discuss if this wording is fine and if it not - what changes are needed.

**Comment by fossfreedom** [comment]
I'll create a branch for this.

You'll quickly realize how annoying that tooltips appear on the playbar

As I mentioned previously - the standard Gtk widget StackSwitcher which is now used on the headerbar listview/coverview doesn't support tooltips - odd yes - presume some upstream reason.

**Comment by me4oslav** [comment]
Well, if they suck that much - we nuke them.
(Gotta file that issue about the radio pane too ...)

**Comment by fossfreedom** [comment]
you can see this yourself actually - just edit the glade file ui/alttoolbar.ui and add something like this to each button property.
    
    <property name="tooltip_text" translatable="yes">Let the plugin determine if to display either the CSD or Toolbar depending upon the desktop-environment running.</property>

**Comment by me4oslav** [comment]
Will test in the morning.

**Comment by me4oslav** [comment]
Hmm, I've added tooltips and they don't seem that annoying, really.
Should I propose a merge request? Or upload to "tooltips" branch? Or just push to "master"?

**Comment by fossfreedom** [comment]
:) - think most opensource developers are a little bit crazy

ok - I'm going to add a kill switch so that tooltips are a configurable item.  Push your changes to master is the easiest.

Remember - the tooltips are going to have to work across sources - so "Play the next song from the tracklist" will not work on the podcast source - they are podcasts, not songs.

BTW - just like the radio source issue - I'm going to change the CSD bar "songs" to "Podcasts" when the podcasts source is activated.

**Comment by me4oslav** [comment]
Right, so we need more clever wording.
Any ideas?

**Comment by fossfreedom** [comment]
common RB parlance is "track" - it is rather generic but covers a multitude of sins

thus maybe "Play the next track", "Play tracks in a random order"

**Comment by me4oslav** [comment]
Pushed to "master" with the new wording. Add a checkbox in prefs to disable them.
Lets keep this bug open until the checkbox is implemented.
