### ISSUE TITLE
Podcast Category

### ISSUE THREAD

**Issue by Foggalong** [fossfreedom/alternative-toolbar#35]
![screenshot_2015-04-23_19-39-06](https://cloud.githubusercontent.com/assets/5920259/7304603/71b379dc-e9f0-11e4-82de-0ec19d1e380a.png)

I'm not entirely sure on Podcasts being an online source. I get the logic behind it, but it just doesn't fit in with the others. Radio, Last.fm and Libre.fm (along with the others which are available via plugins) are all online streaming services. Podcasts on the other hand passively download from RSS whenever Rhythmbox is open so the content can be (and has to be) listened to locally.

**Comment by Foggalong** [comment]
To clarify this isn't a big issue, just something I'd noticed. I'll take this opportunity to thank you for making all the changes modular too - the plugin has breathed a whole new lease of life into Rhythmbox :)

**Comment by fossfreedom** [comment]
@Foggalong 

  your argument does make sense - podcasts are one of those that could be arguable on both local and online sources.

Given that it was @me4oslav that did the design, I'll let Georgi pitch in first before any potential changes.

**Comment by me4oslav** [comment]
It fits both categories, yes. I will look at this in the morning.

**Comment by fossfreedom** [comment]
@me4oslav - gentle prod - happy to make this suggested change?

**Comment by me4oslav** [comment]
@fossfreedom What is the change? Moving to local sources?

**Comment by fossfreedom** [comment]
yep - one line change.

**Comment by me4oslav** [comment]
Guess so.
