### ISSUE TITLE
[DESIGN] Plugin settings redesign.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#38]
Wireframe:

![plugin s preferences](https://cloud.githubusercontent.com/assets/1658870/7394550/fef68194-ee9c-11e4-812a-ebe8eb4e75a4.png)

How an active button looks like:

![screenshot from 2015-04-29 17 09 19](https://cloud.githubusercontent.com/assets/1658870/7393612/83a94ee0-ee97-11e4-91c9-2b0996ebbcd9.png)

It also needs more padding than it currently has right now.
Should I try to Glade the wireframe?

**Comment by fossfreedom** [comment]
yes please - a glade version would be useful.

Hide Playing Controls is missing from the sketch

Volume Control and Hide Playing Controls is applicable to all combinations.

So how do you NOT use headerbar in gnome-shell? - is that when "Modern" is OFF ?  Is "Modern=On" the same as "Auto".  

How do you force headerbar for XFCE/Unity - these would not default to headerbar mode by default.

**Comment by fossfreedom** [comment]
in GTK I've not seen a "Green button" - is this a forced Green coloured Button i.e. does not use the theme styling colour?

**Comment by me4oslav** [comment]
"Show:
<checkbox> Playback Controls"
is the "Hide Playing Controls". :)

I know that volume control works in all the cases.

About the toolbar mode concerns:
If Rhythmbox is used in lets say Gnome the switch for "Modern" will be enabled automatically out of the box. If however it is used in for example Unity - the "Modern" switch will be disabled automatically by default. If in case 1 the user wants a toolbar - he can just switch the "Modern" to "OFF" and if in case 2 the user wants to force a headerbar, he can just flick the "Modern" to "ON".

I dunno what is the exact class for the green button, but I am sure it is a stock widget and uses GTK theming, so no custom stuff needed. For example the "Take Screenshot" in gnome-screenshot is that active button.

**Comment by fossfreedom** [comment]
:) ok - you've just inverted the text meaning - no wonder I didnt see it.

Thanks for the hint about gnome-screenshot.  Green is not the adwaita colour button - that must be your theme colour (its a bluish colour in gnome-shell under ubuntu 15.04).  It looks like its hard-coded - the colour of the button is the "selection" colour of the theme.

**Comment by me4oslav** [comment]
Sorry for the unintentional trolling. :P

I did this with Glade:
![screenshot from 2015-04-29 19 35 43](https://cloud.githubusercontent.com/assets/1658870/7396130/507933b8-eea7-11e4-885a-9907c41200d3.png)

Missing things are:
  -  The "Use compact controls" checkboxe and label do not get inactive when "Modern" is "ON";
  -  The "Restart" button is not active.
  -  Because I have not hooked it all to gsettings this breaks the plugins settings;
  -  The IDs in Glade are less then perfect;

Here is the Glade file:
https://dl.dropboxusercontent.com/u/2656555/altpreferences.ui

Aaaaand have fun fixing the bugs. :)

**Comment by fossfreedom** [comment]
ok - now on the "preferences" branch is I think the fixed up version of your design.

Note: LibPeas defaults to the close button on the bottom right.  You cannot add your own custom button to this dialog - hence why "restart" has to exist within the main content-area of the dialog.

Let me know what you think.

**Comment by fossfreedom** [comment]
correction - rhythmbox itself is creating the preferences dialog - I cannot influence this until the libpeas issue is sorted.

**Comment by me4oslav** [comment]
Libpeas hates up. :is there upstream issue opened for that in bugzilla?

**Comment by fossfreedom** [comment]
I was referring to this issue - https://github.com/fossfreedom/alternative-toolbar/issues/37

When I get some time I'll have a look if the current investigations on #37 actually allow me to reimplement the plugins screen without referring to the libpeas team.

**Comment by me4oslav** [comment]
Okies. Some days I think it will be easier to write a new player with PyGTK3 as a fronted and gstreamer as a back end just so we will have less silly limitations. :)

**Comment by fossfreedom** [comment]
find 10-15 developers ... dreams will come true :P

I  think #37 is actually possible - cannot confirm though until I dig through the limited libpeas API that is available.

Anyway - if you are happy with the current preferences implementation - I'll merge with master.

**Comment by me4oslav** [comment]
I will test in the morning.
Right now I am in no condition to test, 'cause alcohol and weird chatting with former classmates.

**Comment by fossfreedom** [comment]
:)

**Comment by me4oslav** [comment]
Considering that it is impossible to nuke the "help" button and replace it with the "restart", I would say it is good enough to be merged in master.
I just refined the tooltips a bit in the branch:
https://github.com/fossfreedom/alternative-toolbar/commit/b3ae1419dee37502686707c814725b22df910eaf
It is greenlit for merging from my end. If you are OK with it too - merge the "preferences" branch with "master".

**Comment by me4oslav** [comment]
Oooops, I forgot to mention - if new options are to be added they should go like this.
In "Show" pane options that when enabled do not replace / modify any part of the UI. For example if one enables the "Volume control" it will not replace any part of the UI.
In "Use" pane options that when enabled replace / modify some part of the UI. For example if one enables the "Enhanced" sidebar, it will replace the stock sidebar.

**Comment by fossfreedom** [comment]
thanks.  Will remember that.  Stuff merged.

**Comment by me4oslav** [comment]
Okies. Is the "preferences" branch still needed?
