### ISSUE TITLE
[DESIGN] Borders.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#39]
This is more of a papercut bug.

Here is a screenshot of the current rhythmbox with this plugin enabled:

![screenshot from 2015-05-01 15 04 07](https://cloud.githubusercontent.com/assets/1658870/7429948/8f2c5ff0-f013-11e4-832c-0c5a6ee5623a.png)

Now here are the issues:

  -  Right from where the tracklist starts X axis wise there is a some second headerbar border below the standard one;
  -  Tracklist should get borderless (without top, bottom and left borders) and get expanded to the bottom end of the headerbar, top end of the playbar and right end of the sidebar;
  -  Sidebar needs border on the right - https://github.com/fossfreedom/alternative-toolbar/issues/21

**Comment by fossfreedom** [comment]
I'll have a look at the first.

re the second - probably can be resolved by some-sort of CSS theming.  CSS is not something I'm familiar with - I can add a hook for you/someone to fiddle with.

Re the side bar - yeah. Dunno how to do this in GTK.

**Comment by me4oslav** [comment]
@satya164 is quite good with CSS. Satya, any help?

**Comment by fossfreedom** [comment]
note - I'm using rhythmbox 3.2 which had a whole lot of CSS theming changes done to it.

looks like most of your issues have been resolved:

![pic](http://i.imgur.com/jTY2OgM.png)

**Comment by me4oslav** [comment]
Except the sidebar border and tracklist stretching.

**Comment by fossfreedom** [comment]
you can investigate the various Gtk settings - press CTRL + I to start the inspector.

Under the GTK Grid you can see that there is a margin-top value of 6 - I can code that as zero - so that particular issue can be solved.  This gives a view like this.

![pic](http://i.imgur.com/PVoJdfD.png)

This is Ubuntu 15.04 - i.e. GTK+3.14 Adwaita.

I'm getting a bit lost here with the suggested "sidebar border" - its visually differentiated on that screenshot.

Also - note the sidebar - there is a definite space between the application edge and the expanders - its approx 5 pixels.

**Comment by me4oslav** [comment]
Borders wise your screenie looks OK, except the dual border n the bottom of the headerbar.

**Comment by fossfreedom** [comment]
Hmm - looks like a GTK bug - using the GTK Inspector (CTRL+I) if you set the GtkSearchbar visibility to false it removes that.  For some reason GTK is displaying a 1 pixel lower border of the searchbar even though the searchbar is "hidden"

Looks like I need to set the visibility of the searchbar to "false" when the search button is not depressed.  Will look into that.

latest picture with visibility = false for the searchbar, small toolbar, left aligned with spacing of 5 pixels left and bottom

![pix](http://i.imgur.com/d05AcVu.png)

**Comment by me4oslav** [comment]
That looks quite good!
Just the dual headerbar border bug caused by the searchbar and the missing top border on the inline toolbar with the +-^ to go. :)

**Comment by fossfreedom** [comment]
the tracklist papercut which is the central focus of this issue has been resolved.  Now merged with master.  Anything else should be a separate issue.

**Comment by me4oslav** [comment]
Ok, everything seems fixed with Adwaita and Numix. Ozon GTK has bugs that there are no sidebar and inline borders, but like I said - these are theme bugs and we will fix them.
