### ISSUE TITLE
moving the secondary toolbar into the CSD

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#4]
The find option to toggle the visibility of the secondary toolbar might be a starting point here.

This pointer could mean that can actually move the secondary toolbar into the CSD.

Not sure though when & how the "secondary toolbar" that is  now in the CSD should be activated i.e. flip back and forth between the main toolbar and the secondary toolbar.

Anyway - create this issue as a thinking point.

**Comment by me4oslav** [comment]
I have an idea about that. But I need more time to conduct virtual UX tests before I post it.

**Comment by me4oslav** [comment]
Here is extremely preliminary wireframe. I know it is very gnome-music-y (which is because I follow the Gnome design and HIT ;p) and that unholy amount of stuff is missing, but I will fix both.
However I wanna know if it possible to implement it before I do more wireframes.
![screenshot from 2015-03-15 19 20 43](https://cloud.githubusercontent.com/assets/1658870/6657068/8e0f7732-cb48-11e4-8bce-e93babefa44a.png)
Do tell me if it is.

**Comment by me4oslav** [comment]
Here is extremely preliminary wireframe. I know it is very gnome-music-y (which is because I follow the Gnome design and HIT ;p) and that unholy amount of stuff is missing, but I will fix both.
However I wanna know if it possible to implement it before I do more wireframes.
![screenshot from 2015-03-15 19 20 43](https://cloud.githubusercontent.com/assets/1658870/6657068/8e0f7732-cb48-11e4-8bce-e93babefa44a.png)
Do tell me if it is.

**Comment by me4oslav** [comment]
BTW - with this design the sidebar icons (there will no icons in it) don't need fixing and neither does issue #6.

**Comment by fossfreedom** [comment]
That really does remind me of gnome-music

I've raised a [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=733116) a while back about the bottom part of the screen.  Currently there is an issue that you can only place the toolbar from the start of the song view to the edge of the screen i.e.

![Imgur](http://i.imgur.com/ks7uhBF.png)

So - that will need to get fixed first - something that is beyond my capabilities.  Need to find a C programmer that probably could fix this in a day or two worth of effort.  Once that is fixed - then yes - very easy to move the current header bar/compact bar to the bottom of the screen.

The revised header bar is interesting - but really you are verging into rhythmbox territory - not really the ability of a plugin if you are looking for the gnome-music separate album/artist/genre views.  

A plugin such as this could hide the current browser "album - artist - genre" boxes. Then you could filter the main song view by Album/Artist/Genre (certainly with a small bit of work) by - for example - "clicking artist" in the headerbar which would reveal a popup showing all the artists that you normally see in the browser view.  Clicking an artist would then filter the song view.

The search entry bar will again need a small piece of work to work - certainly possible via a plugin again - will take some thinking time on this.

So, lets be positive - you could certainly have something like your mockup - just need to get that bug fixed first.

If you were thinking of getting all of this done by the launch of ozon - unlikely.  Thats ozon + 1 territory.

**Comment by me4oslav** [comment]
You don't have to worry about Ozon's  ETAs. Partly because it is not imperative for Ozon final reason and also because Ozon doesn't really have an ETA.
Yes, it does look like Gnome music and I am aware of the fact that I might be going outside the plugin scope. You know - Ozon would have used Gnome-Music, but Gnome-Music is pretty much impossible to use for a normal person who doesn't put his music in /home/USER/music. If the user is not some sort of a Linux geek and doesn't keep his music in ~/music, he couldn't use Gnome Music. It requires tracker and xdg sorcery to be set up. I don't know why Gnome does that. :(
Anyways, for this may not be possible as a plugin, will it be possible in upstream rhythmbox? I mean - do you have the knowledge and time to do that? Of course that is after the issue that you mention above is fixed.
P.S. I have a simpler design that should be doable to implement inside this plugin. Will wireframe it also.

**Comment by fossfreedom** [comment]
Will it possible in upstream rhythmbox...

well yes  - anything is possible in software.  Will Jonathan, the current maintainer himself do it on his own - unlikely - you'll need a team of at least 2 C programmers to rework rhythmbox to be more like gnome-music. 

Rhythmbox is very well written, very modular and its very straight forward to create new views from the underlying music structures.

And no - not in my gift  - my C programming skills arent up-to this job.  I am very much a python programmer.

BTW - I fully agree with you about gnome-music.  It did have so much promise - but I for one couldnt fathom out why the developers ham-strung the app to using tracker etc.  I've looked at the code and its so endemic it will probably take a rewrite to get the app back to something fundamentally usable & workable :(

**Comment by me4oslav** [comment]
Yes, Gnome music has so much potential, but that tracker and xdg dependance is just horrid. :/
I will make a simpler design tomorrow after I am done with some paperwork.

**Comment by fossfreedom** [comment]
well ... a bit of hacking I've managed to get this...

![pic](http://i.imgur.com/YcsznNl.png)

basically I've fooled rhythmbox to add the compact-bar at the bottom - I've turned off the status bar because that looks a little strange having a full screen-wide status-bar just above the compact-bar.

I've then added the GtkHeaderbar at the top - I've currently just left the title in the headerbar which RB changes automatically to the song being played.

So all in all - think we have the start of something more closely what you envisaged :)

I'll continue playing around to see if I can persuade the RB Search Entry that normally appears in the secondary toolbar (currently switched off) to appear in the headerbar area.

**Comment by me4oslav** [comment]
I will comment in the morning. It is 3 AM right now for me. :P

**Comment by me4oslav** [comment]
Ok, moooorning.

Now lemme comment: 
  - The toggle sidebar arrow on the right is not really needed, I think. Monitors nowadays are wide enough for people to have no need for hiding the sidebar. But for choice's sake lets say some people will want to hide it. For them this button should go in the plugin preferences as a checkbox. I doubt there is a person that toggles the sidebar so oftenly that he/she needs an UI element in the main UI for that. :)
 - The headerbar should become like this: 
<Songs list | Albums and artists> (toggles, in the centre. The first will open this view https://cloud.githubusercontent.com/assets/1658870/6657095/52dd160a-cb49-11e4-89ee-921fdb16854e.png  and the second this one - https://camo.githubusercontent.com/b3db0259c9b53f9a086bc8e24349b68a59923598/687474703a2f2f692e696d6775722e636f6d2f5963737a6e4e6c2e706e67)
<search> (on the right, should toggle just a search field like in System Settings)
 - The toggle betwen all songs and browse by artists and albums view button should go away once the headerbar is implemented as the way described above).
 - The <prev | pause/start | next> should get joined in one multibutton and so should <repeat | shuffle>, but the latter should go on the rigfht of the position slider.
 - The "Import" from the previous "toolbar" should go in the "appmenu".
 - The "Edit" from the previous "toolbar" should be a right click menu.

I could have gone further with that, but I don't wanna go outside the plugin scope (again :P) so I tried to  keep everything relkatively simple. If you can not do the toggles in the headerbar, just tell me, I have even simpler design solution.

**Comment by fossfreedom** [comment]
morning :)

I've kinda got a bit lost with the various suggestions.  When you have a bit of time, any chance of a pencil sketch?

**Comment by me4oslav** [comment]
Just gimme a few mins.

**Comment by me4oslav** [comment]
There you go. :)
P.S. Apologies in advance if you have issues reading my handwriting, but I am from a cyrllic country, hence the letters style.  tried to write as sane as possible.
![img_20150316_122756](https://cloud.githubusercontent.com/assets/1658870/6664436/444d1a38-cbd8-11e4-84b6-e322b64755b4.jpg)
![img_20150316_122815](https://cloud.githubusercontent.com/assets/1658870/6664437/444d85c2-cbd8-11e4-9a09-486bf47dca47.jpg)

**Comment by me4oslav** [comment]
Little change:
The "songs" toggle should be this mode:
![screenshot from 2015-03-16 14 08 38](https://cloud.githubusercontent.com/assets/1658870/6665763/00c85292-cbe6-11e4-830b-b4bad6ac486a.png)
The "artists and albums" - this one:
![screenshot from 2015-03-16 14 08 51](https://cloud.githubusercontent.com/assets/1658870/6665769/12284362-cbe6-11e4-8a00-cab41a1d5b45.png)

**Comment by fossfreedom** [comment]
Thanks for the clarification,

  somethings to think about - so cheers for the pencil sketch.

First thing to do is to see if the search function can be moved into the header bar.  Once I've clarified that we can do this then work on the rest of the stuff which all looks very straight-forward and doable. Possibly will have issues with the Edit and Import buttons.  That will take some thinking.

I'll update you over this week as to progress.  Cheers.

**Comment by me4oslav** [comment]
Import is already "Add music" in the appmenu, so there is no work needed for it. It is the first item, even:
![screenshot from 2015-03-16 14 34 39](https://cloud.githubusercontent.com/assets/1658870/6666111/cad032be-cbe9-11e4-88dd-999b93cb410a.png)
For edit you need to add the "select all" and "deselect all" options, making it a popover is not mandatory. Neither is making the on hover full alnum cover a popover either.

**Comment by me4oslav** [comment]
Here is a digital wireframe too, btw:
![concept](https://cloud.githubusercontent.com/assets/1658870/6684499/c0afedae-cc9a-11e4-9119-6932c859f2d6.png)

**Comment by me4oslav** [comment]
Just tested the Gnome-Shell branch. There are bunch of changes needed, but it is getting there.
BTW, side from the other changes the bottom play bar needs more spacing.

**Comment by fossfreedom** [comment]
patience ... I tend to upload stuff for backup purposes.  Its not ready yet!

I'll let you know when I've got stuff in a usable state.

**Comment by me4oslav** [comment]
I know. I just saw the gnome-shell branch and couldn't resist installing it. :P

**Comment by fossfreedom** [comment]
BTW - what GTK widget is that play/pause/stop button supposed to be?

**Comment by me4oslav** [comment]
I have no idea, but it should be possible on theory. Anyways, the centre button in the joined <prev|play/pause|next> can just be play/pause one and stop can not be implemented, it is not a necessity. It can be added later on as an option in the preferences that will display a stop button next to the play/pause one in the joined button.

**Comment by fossfreedom** [comment]
Hi,
  re the search button - how did you envisage that working?

For example - clicking the button hides that button and replaces it with the search entry field with the focus already set in the entry field?
How do you go back from the search entry field back to the search button - by losing focus ?

**Comment by me4oslav** [comment]
Nothing fancy for the "Search", just like the Search in System Settings.

**Comment by fossfreedom** [comment]
so - clicking the toolbar button hides the current headerbar contents and moves the toolbar button to the left-hand side and adds the search entry to the right-hand side.

To get back to where you were - click the toolbar button on the left ... or click  another music source such as the queue or playlist ?

**Comment by me4oslav** [comment]
Oh no. It is much simpler. :)
Clicking on it just opens a temporary bar with search box in it below the headerbar:
![screenshot from 2015-03-21 10 51 17](https://cloud.githubusercontent.com/assets/1658870/6764436/4f41dbf2-cfb8-11e4-9869-117d94e090c0.png)
Unclicking on it just hides that bar and box:
![screenshot from 2015-03-21 10 51 04](https://cloud.githubusercontent.com/assets/1658870/6764439/62522e2c-cfb8-11e4-9d50-58f45257df12.png)
Search shouldn't all touch the headerbar items.

**Comment by me4oslav** [comment]
Oh and those toggles on top:
![screenshot from 2015-03-21 11 03 30](https://cloud.githubusercontent.com/assets/1658870/6764484/f2ff9788-cfb9-11e4-9540-c8d9257305b1.png)
Should be the same widget as the breadcrumbs in nautilus:
![screenshot from 2015-03-21 10 55 04](https://cloud.githubusercontent.com/assets/1658870/6764486/00cdc268-cfba-11e4-8ee3-7bfb52411396.png)

**Comment by fossfreedom** [comment]
thanks.

From gtkinspector those breadcrumbs are a pair to GtkToggleButtons - odd choice since GtkRadioButtons (as currently implemented) are inherited from GtkToggleButtons and perform the toggle effect better IMHO.

The search thingy looks to be a GtkRevealer showing a GtkSearchBar.  I've looked at the new Gnome Settings in Gtk3.14 and I really dislike immensely how the whole window shifts down when the GtkSearchBar is shown.  It looks and feels very odd.

**Comment by me4oslav** [comment]
I am not a fan of the Search thing either, but it is HIG thing. 
Alternate way would be dsiplaying a poover with a search box when the user has clicked the search button. This wouldf also not break the HIG and on theory in should be simpler to implement.
Regarding the toggles - what I was planning were toggles like in Gnome-Music widgets wise:
https://afaikblog.files.wordpress.com/2011/11/music-albums.png
Oh and "Albums and artists" should get rnamed to "Categories".

**Comment by fossfreedom** [comment]
ok - that's better.

On Gnome-Music that widget is a GtkStackSwitcher - so nautilus is not a good app to follow from a standard Gnome application-look-and-feel point-of-view - it doesnt follow any standard widget guidelines... its all custom code and custom styling.

"Categories" doesnt really mean very much to me - remember you set the browser-view type via rhythmbox - preferences.  So there are different browser-views available.  For the moment I'll use "Categories" as the button label but may have to revisit this later.

**Comment by me4oslav** [comment]
Good to see we settled on Search on Toggles design.
Regarding that label, it is something that can summarise all this categories? Got any better idea than "Categories"?
![screenshot from 2015-03-21 13 27 04](https://cloud.githubusercontent.com/assets/1658870/6764851/1056568c-cfce-11e4-97ae-d9e98b3c345f.png)

**Comment by fossfreedom** [comment]
ok - the code is very scrappy ... and the search bar only really works for the music view ... but this is all fixable.

Have added the search button.  I've used a GtkButtonBar instead of a GtkStackSwitcher simply because the StackSwitch widget doesnt have a means to understand when a user actually clicks a button.

**Comment by me4oslav** [comment]
there Good job. Surely enough there is work to do, like the issue you mention above and for example the fact that the bottom buttons miss the framing, but is is definitely getting there.
In addition I found one more bug. When I start the player the active toggle is the <Songs> one, but I am infact in the <Categories one>. Here is a screenshot:
![screenshot from 2015-03-21 18 44 48](https://cloud.githubusercontent.com/assets/1658870/6765887/80ac18b4-cffa-11e4-9cb3-dc51d4011c2a.png)
I am fine with the player starting in <Categories>, but if so the active toggle should be the categories one.
To fix that now I've to go click <Categories> and then <Songs>.
BTW, are you sure you wanna stick with the sliding bar for Search? Not that I mind that either, but you said you don't like it much, hence I suggested a popover.

**Comment by fossfreedom** [comment]
GtkPopOver only works for GTK3.12+ users ... so Ubuntu 14.04 trusty users wouldnt be able to use the plugin.  I'll have a look a little later with which route I want to take ... but first I want to fix the code and polish it.  Just wanted to give you a heads-up of progress so-far.

I've just fixed that category issue.  I'll add the framing for the buttons later.

**Comment by me4oslav** [comment]
Oki-doki. Looking forward to the next update. :)
Great job, so far!

**Comment by me4oslav** [comment]
YAY, framing and lack of arrows.
The buttons for previous,play/pause/next are quite long, though and there are way too much margin on the of that joined button.
![screenshot from 2015-03-21 20 35 09](https://cloud.githubusercontent.com/assets/1658870/6766315/f955f4ba-d009-11e4-9124-bd4c8798171d.png)

**Comment by me4oslav** [comment]
Yay, the issues from above is gone.
There is still work to be done until it meets the design specs, but it is definitely progressing at fast tempo! Keep up he fantastic work.

**Comment by me4oslav** [comment]
I guess an easy fix would be to make the bottom play bar use the same sizes as gnome music: 
![gnome-music](https://cloud.githubusercontent.com/assets/1658870/6768797/2e10f99c-d088-11e4-9580-66a14cd7cfb8.png)
Especially the cover art size, RB uses 26px, whilst GM uses 34.

**Comment by me4oslav** [comment]
For testing purposes I enabled the volume control and it doesn't seem to use symbolic icons.
![screenshot from 2015-03-22 14 34 59](https://cloud.githubusercontent.com/assets/1658870/6769359/ba689270-d0a0-11e4-9a30-f2fa9a0bbaad.png)

**Comment by me4oslav** [comment]
Just tested the latest branch and all I can see for fixing is:
A) Bottom bar does not completely meet the design specs:
![screenshot from 2015-03-24 12 27 02](https://cloud.githubusercontent.com/assets/1658870/6799812/88e4523e-d221-11e4-8696-bc1d6ba2447a.png)
![screenshot from 2015-03-24 12 32 36](https://cloud.githubusercontent.com/assets/1658870/6799850/e11008fe-d221-11e4-8aa2-c24ef0752302.png)
If you ignore the stop button thing-y, what remains t be fixed in it is just papercuts, so they should be relatively easy to fix. :)
B) The right click edit menu misses select and deselect all options.
Really amazed by your implementation so far!
P.S. We (Ozon) might consider implementing the coveart plugin too.

**Comment by fossfreedom** [comment]
Future plans... below is some of my immediate thoughts and ramblings.

For A:

 what I plan to do is move the elapsed time and song duration from current to the design spec position.

I'm not happy with the album title and album name move to before the  slider.  I've got a standard laptop 1280 wide and I do not run rhythmbox full screen.  Thus the design spec would mean a very small slider which makes scrobbling hard to do.  Most albums I have, have album titles/names much longer than in the spec.   One of the main reasons why I created the plugin in the first place is that I disliked the small slider in the current RB design.

I was thinking of making this a future enhancement where the song title/album title moves to the paper spec position BUT ONLY when there is sufficient application screen width to allow an adequate slider bar + album title/album name.

Maybe again it could be a configurable item ... thus it could be for any distro to set the configuration items they particularly want to use in their software package.

Displaying the album-art as a GtkPopOver - is a papercut enhancement.

I've been going back and forth with splitting the shuffle&repeat buttons as per the spec or moving them together  as per current implementation & current rhythmbox.  Personally I prefer the combined look.  It feels better to me.  

I'm also thinking through how to do the "stop drop-down" arrow thingy.  I get the impression looking at gnome-music that a similar button is displayed all the time.  Visually it just looks odd in the screenshots that I see - the arrow is too large.  I get the impression Gtk forces you down this route - not something I like.

The repeat button is likely to get an enhancement to allow you to repeat all songs (as current) as well as repeat-one-song.

B) Yes - the select all/deselect all is a papercut issue - this can be done.

BTW I'm in the middle of restructuring the plugin to make it easier to understand and most importantly maintainable.  I'll be working behind the scenes on this all of this week (as time allows obviously).  I'm setting myself a deadline of merging the gnome-shell branch with master by COP sunday week (week after next).  i.e. fully tested - then again, refactoring is going well so maybe sooner.

Re: coverart - nice!  I'm thinking of using the left-hand side of the header bar to add the "..." drop-down button to switch to the various views available in coverart (if the plugin is enabled).  Maybe/maybe not.  I'll play around to see what feels usable.

During my testing I'm going to have a close look at each of the rhythmbox sources (the stuff in the side pane - for example magnatune/last fm) and make sure the functionality that was in each source is actually available via "songs"/"Categories" buttons as well as the App-menu.  If there is a toolbar button that is not covered by "songs"/"Categories" or the app-menu then the left-hand side of the header bar might be a good candidate to relocate that button but only displayed in the headbar if the source has focus.

Paper cut issues and other enhancements above I'll probably create individual issues to consider afterwards.

Anyway ... enough rambling.  back to (real paid) work.

**Comment by me4oslav** [comment]
If repeat will get an the enhancement to repeat all songs and current one it will have to be a single button like this:
![screenshot from 2015-03-24 14 51 18](https://cloud.githubusercontent.com/assets/1658870/6802027/815b9a68-d235-11e4-8404-5a4a027aebcb.png)
This is also how the arrow for the stop button should look.
Regarding coverart - what i was thinking f making it a toggle button in the headerbar and right of it and categories have that same exact arrow on which when you click you get a menu with the options. For example for categories you will get drop down menu with three options - artists, album, genres. However this is just a crude idea that may suck at reality. Need to do tests and sketches and studies for that.
Let us first see it with the papercuts fixed and then we can go further.
P.S. When the elapsed / full time gets moved right of the slider - add a little spacing between it and the slider, cause now with 0px of whitespace it looks bad as you can imagine.

**Comment by fossfreedom** [comment]
from a HIG point-of-view - what do you think about revealing that arrow only when the mouse is within the button space - or if the button has focus?

**Comment by me4oslav** [comment]
For the bottom play bar it should always be there, but I am unsure if it is even allowed by the HIG for the top categories bar toggles. I need to read the hig better regarding those and see what we can do about that navigation.
Oh and just noticed - pressing space stops the song instead of pausing. Where should I report this? A new issue here? Ne upstream issue in Bugzilla?

**Comment by fossfreedom** [comment]
space never pauses - https://bugzilla.gnome.org/show_bug.cgi?id=326066

ctrl+space I think is the shortcut.

**Comment by me4oslav** [comment]
I see the spacing and the elapsed time / full time are fixed. One tiny papercut to fix would be putting spaces before and after the  "/" in that element.
So, what is left to do is additional option to display the slider, song name and artist name and the time like this:
![screenshot from 2015-03-25 13 25 11](https://cloud.githubusercontent.com/assets/1658870/6823597/641b8b26-d2f2-11e4-91fe-a577d1c39d83.png)
And then what is left to do is the select and deselect all in the right click edit menu.
When those are implemented the first batch of design changes will be done and then we can start thinking about the rest like coverart and repeat buttons options ad etc ...

**Comment by fossfreedom** [comment]
ok - I'm now going to work on making sure that the search facility works across each library source

![pic](http://i.imgur.com/nDvtjjf.png)

Looking at the play-queue I can do exactly the same as the Music Source - just have a search bar revealed by the search icon in the header bar.  As you can see lots more buttons to play with here.  I can move each of these into the same search-bar.  What do you think with this approach?

**Comment by me4oslav** [comment]
I should really be sleeping now. Will tell you when I wakeup.

**Comment by fossfreedom** [comment]
night! ... or good-morning (by the time you read this) :D

**Comment by me4oslav** [comment]
Ok, I am a bit list with your latest comment. Can you reword it?

**Comment by me4oslav** [comment]
Sorry for the recent absence, but my health has been (and still is) so incredibly wonky that this project got placed in a backlog until now.
Now:
 - YAY the progress bar has scrobbling. I was about to report that, but the latest version seems to have that fixed.
 - When I enable "Show Source and Media Toolbars" from Apmmenu -> View I get this bar:
![screenshot from 2015-04-02 13 31 35](https://cloud.githubusercontent.com/assets/1658870/6965506/b26f22b0-d95a-11e4-966d-0384f05cbfdf.png)
which I dunno why it is revamped when "Import" is in the appmenu -> add music, "browse" does not seem to do at all and edit is the right click on a song menu and the select and deselect all options, which should get added to it anyway.

**Comment by fossfreedom** [comment]
Hi  again - bed rest is recommended :)

  yep - I'm nearing the end of the code refactoring - so I should (in theory) now be able to code way specific buttons like View All and Import with relative ease.  Still on target to merge the work up-to master by the end-of-the-weekend.

I'm just making the final tweaks for your design to allow you to put the album name/album title in-line with the scrobble  bar.  I'lll finish that tonight.

Raise a separate issue on the coverart-browser project and I'll help you get it to install - you are probably just missing a dependency that I'm not aware of on fedora - if you run "rhythmbox" in a terminal and activate the plugin it should give you some idea what the issue is - a hint to what extra needs to be installed.

I noticed one of your ozon commenters mentioned the dislike of the list of sources (left hand side of the application).  Is this something you want me to look at?  It should be possible to add a button to the headerbar (next to the search button?) which does a PopOver displaying  the sources scroll-window.

**Comment by me4oslav** [comment]
Oki, I will monitor for changes.
Filing an issue in the coverart repository right now.
Sidebar wise - maaaaaaan, sometimes I think that sidebar is the worst. We should improve it a lot too. But lets first finish this badge of changes. Than we can start on coverart and sidebar.

**Comment by me4oslav** [comment]
There - https://github.com/fossfreedom/coverart-browser/issues/357

**Comment by me4oslav** [comment]
BTW, where do I open sidebar design issues?

**Comment by fossfreedom** [comment]
re sidebar issues - suggest just create a new issue - we can discuss what the art of the possible is.

**Comment by me4oslav** [comment]
I found tiny issues with the inline displaying. When enabled:
A) The slider and the elapsed / full time things must be in the centre Y wise to the coverart, not to the bottom;
B) There is not enough spacing between the slider and the label on the left and the time on the right
![screenshot from 2015-04-03 11 46 03](https://cloud.githubusercontent.com/assets/1658870/6980357/331e00d6-d9f9-11e4-9bdf-3da89c820e20.png)
For tasting purposes I enabled the volume control and the button misses the framing.

**Comment by me4oslav** [comment]
Oh and the repeat and shuffle stopped working for me again.

**Comment by me4oslav** [comment]
All the issues above except for spacing between the slider and the song and artist name and slider centring Y axis wise (needs to be a few px to the top) are fixed. Good.
I created sidebar issue too:
https://github.com/fossfreedom/alternative-toolbar/issues/13

**Comment by me4oslav** [comment]
Just noticed the slider used is not the slider widget we need. The one we need is:
![screenshot from 2015-04-03 15 58 06](https://cloud.githubusercontent.com/assets/1658870/6982420/43100a90-da1a-11e4-9d93-2097c21d5a39.png)
I believe what we need is quite standard GTKScale.

**Comment by fossfreedom** [comment]
ok - corrected the Y axis issue and increased the space between the song and slider.  If there are any other padding issues, please give me the revised alttoolbar.ui padding values.

I'm not using the standard GtkScale deliberately - it's too large when using my preferred look which is the combine song/artist & scrobble bar.   For the moment, I'll create another issue and I'll consider adding this at some future time.  Right now its not a priority for this version of the plugin.  I want to finish the source toolbar button issues before merging with master.

**Comment by me4oslav** [comment]
Source toolbar? Is that the one with the Edit View All Import ... ?
'Cause we don't need that one.
Yay extra bug reports.

**Comment by fossfreedom** [comment]
yep - in rhythmbox speak - everything you click in the sidebar is a "source" - and every source can have its own toolbar hence "source toolbar".

A few external plugin writers do add extra menu options to the "Edit" menu button.  Some plugin writers such as myself (coverart browser) add extra menu buttons to the source toolbar.  

Thus - this is why we cannot just lose the entire toolbar from the design otherwise you'll have users who lose access to their favourite plugin.

I'm going to remove "view all" from the toolbar - its pretty redundant functionality since it only works if you've got the "categories" option chosen and its minor functionality anyway (it resets the category options if you have chosen anything)

I'll also remove the Import option since as you have noticed it is duplicated in the application menu anyway.

I'll leave the Edit toolbar so that we dont break other external plugins.

**Comment by me4oslav** [comment]
I have some thoughts about that, but the sedatives that I just drank make me extremely sleepy. Will write in the morning.

**Comment by me4oslav** [comment]
Right, lemme type what I wanted to type tonight.
Firstly - if I want the inline toolbar for the sidebar (with +-^) I have to enable the source toolbar too. Are these two connected in any logical way so they both have to be either off or on?
Next up - it seems to have a "..." button, but I dunno what does it do?

**Comment by fossfreedom** [comment]
The ... is from coverart - choose one of the options and you'll switch to that view.  Untick coverart-browser from plugins and you'll see that button disappear from Music Library & Play Queue.

We could - for example - think about moving/replacing the "song/category" buttons if coverart-browser is enabled.  

Thinking out loud here... if coverart-browser is enabled then

1. Move the category button to the left-handside of the header bar.  This will be only visible for views that are "browseable" e.g. Music Library, Playlists
 
2. In the middle of the header bar where song/category is currently in position,  we could think about adding buttons/icons for various views e.g. button for song - album - artist etc - maybe something like gnome-music.  
a. Clicking song goes to the Music Library view, 
b. Album goes to the CoverArt Browser Tile view (displays albums), 
c. Artist goes to the CoverArt Browser Artist view 

The only reason you ever need to display the inline toolbar (from the application menu or by pressing CTRL+T) is if you need to see and use one of the options.   As I have said previously, other plugins do add various menu items/new buttons to the inline toolbar so we cannot permanently hide this... except - for example - use the search button to display the inline toolbar options as well as the search entry field.

The only reason I tied the +-^ mini-toolbar with the source toolbar was because of a couple of people commenting on your Ozon google thingy a couple of weeks ago that they really disliked that extra toolbar always being displayed.  If you want to untie that and make that +-^ toolbar always visible, that is a simple one-line change - I can unhook that very simply.  

The +-^ options are actually very rarely used unless you happen to create delete lots of playlists, or play CD's where you want to eject the CD.  Myself, for example, hardly ever use that +-^ mini-toolbar.

Let me know what you think.  I happy either-way - display always, or to make it optional.

**Comment by me4oslav** [comment]
Ok, lets unhook the inline and the other toolbar, keep them inline disabled by default (with a checkbox in view to enable it) and the other enabled only when the user is in plugin (as in in the plugin screen, not just having the plugin enabled) that has a need for that bar.
Coverart design wise - first finish this badge of the redesign (there are three issues still standing and you have some refactoring left) and then we will start on the coverart. I even have an ace up my sleeve for it that will allow us to utilise the headerbar more, because right now it is kinda empty. But finish the other stuff too.
P.S. I wrote to the Linux Action Show about this work we're doing and they might mention it which will bring popularity and maybe contributors.

**Comment by fossfreedom** [comment]
will unhook +-^ and make it permanently visible.

Remind me - three things to-do?

BTW - refactoring is complete - just bug-hunting and code comments need to be add.

**Comment by me4oslav** [comment]
Three things would be #14 , #15 and #16.
Make the inline toolbar able to be disabled, though.
So - inline fix, the three bugs fro above, bug hunting and code comments and then it can end up in master. After that we can focus on sidebar and cover-art.

**Comment by fossfreedom** [comment]
15 and 16 are enhancements - and I disagree fundamentally with the approach of displaying the arrow permanently.  If that is Gnome HIG - then its poor visual design for me. 15 and 16 will need to wait until I find time to see what works best for me.

14 I'll have a look soonish.

**Comment by me4oslav** [comment]
Yeah, that arrow is a HIG thing. I guess Gnome's logic is that this way the user knows for sure there is an additional option and buttons that change size (which maybe cause window rearranging). It is not the prettiest thing out there, but it seems like a reasonable compromise. We've been following the Gnome HIG so far, not sure we want to break it.

**Comment by fossfreedom** [comment]
I'm sure we can do better - we are changing stuff pixel by pixel.  

Lets not go and ruin things where stuff is clearly wrong.  

As I said - I'm going to play around with some ideas.  The fact that you've padded the buttons is actually good news - think we can do something by changing the appearance logically when mouse-over the button without breaking the overall size of the play-control.

**Comment by me4oslav** [comment]
Just thinking out loud here. Let's say we display the arrow only on hover. That leaves two possibilities:
  -  make the button longer when on hover due to the arrow;
  -  display the arrow in the padding space which would mean same width button, but also an inconsistent padding wise on hover button;

**Comment by fossfreedom** [comment]
@me4oslav - thanks for all of your help with this issue.

I've tidied up and now merged with master.

Onwards and upwards :)
