### ISSUE TITLE
[DESIGN] Enhanced sidebar padding on the left.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#40]
Screenshot:

![screenshot from 2015-05-01 15 12 56](https://cloud.githubusercontent.com/assets/1658870/7429989/8fdbc430-f014-11e4-9ee9-5c83c8a8d77f.png)

It can use some padding on the left. The elements can start a few pixels more to the right.

**Comment by fossfreedom** [comment]
this appears to be a theme issue.  Problem isnt observed on Adwaita.

**Comment by fossfreedom** [comment]
I've added a fixed width column of 5 pixels at the start of the treeview - this seems to work ok with Ambiance and doesnt look out of place with Adwaita.

Have a look at the commit - you can fiddle with the value "5" with whatever you want here (line 106)

**Comment by me4oslav** [comment]
It is fine now. Closing this bug.
