### ISSUE TITLE
[DESIGN] Enhanced sidebar should remember subcategories expand-collapse states.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#41]
Test case:
  -  Enable the last.fm plugin and login with your credentials in it. Make sure you leave the last.fm category collapsed;
  -  Restart the player;
  -  The last.fm sucategory will start expanded, despite that you've left it collapsed;

**Comment by fossfreedom** [comment]
ok,
  I've slightly reworked this so that the subcategories dont automatically open when clicking on rows.

Also - dont automatically open when first start RB and categories are shown.

This works better and is more intuitive.

**Comment by me4oslav** [comment]
The issue is gone. Closing this.
