### ISSUE TITLE
[DESIGN] About Dialog redesign.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#43]
Wireframe:
![screenshot from 2015-05-07 16 55 28](https://cloud.githubusercontent.com/assets/1658870/7516743/e64b45a6-f4d9-11e4-95a5-70e98e03cc76.png)
I did this in Glade:
![screenshot from 2015-05-07 16 56 58](https://cloud.githubusercontent.com/assets/1658870/7516779/173f0972-f4da-11e4-80ea-cdceea8c2d67.png)
But it is quite imperfect.

**Comment by fossfreedom** [comment]
thanks - just push the glade file into the plugins branch and I'll tidy it up according to your wireframe.

**Comment by me4oslav** [comment]
Just did that.
Note that apart from the other things you have to fix (CSD, centring, bottom buttonand yada yada)  our names should become link buttons that lead to our GH profiles, homepage should lead here https://github.com/fossfreedom/alternative-toolbar and help here https://github.com/fossfreedom/alternative-toolbar/blob/master/README.md

**Comment by me4oslav** [comment]
Just tested it and found two issues:
  -  The:
    -  Developer: David Mohammed
    -    Designer: Georgi Karavasilev
labels should get moved a few pixels to the left, because they are not centred X axis wise;
  -  The diaog should not be resizable for it displays all the info in the default size;

**Comment by me4oslav** [comment]
Just one last thing, isn't it a bit too wide now?
![screenshot from 2015-05-09 11 46 04](https://cloud.githubusercontent.com/assets/1658870/7549521/27cb045e-f641-11e4-8a4c-69861a7d6e63.png)
That's because previously the description was on multiple lines and now it is on a single one.

**Comment by fossfreedom** [comment]
yeah - I noticed that as well.  I'm not setting the window size in anyway now after your last request

it seems GTK wants to resize the window that way when you turn-off the resizable window option.

Setting the default window size is not possible when you turn off the resizeable window option.

**Comment by me4oslav** [comment]
Damn GTK. :/
Anyway around this?

**Comment by me4oslav** [comment]
All right, last two very minor details:
  -  isn't the spacing between the different labels a bit too much?
  -  The label "Designer:" should end right where the label "Developer:" ends, X axis wise;
