### ISSUE TITLE
Some translations for the CSD toolbar

### ISSUE THREAD

**Issue by sergioad** [fossfreedom/alternative-toolbar#44]
Hello @fossfreedom @me4oslav I have two translations for the CSDs

Lang = es / es_ES es_MX and many other
1.- Songs = Canciones
2.- Categories = Categorías 
3.- Use = Usar
4.- Compact progress slider = Deslizador de progreso compacto
5.- Enhanced sidebar = Barra lateral mejorada
6.- Modern = Moderno
7- Use compact controls = Usar controles compactos
8.- Album/genre/year for playing song = album/genero/año para la canción en reproducción
9.- Playback controls = controles de reproducciónn
10.- Volume control = Control de volumen
11.- Tooltips on playback controls = Consejos en los controles de reproducción
12.- Restart = Reinicar
13.- Resume or pause playback = Continuar o pausar la reproducción
14.- Play the next track = Reproducir la siguiente pista
15.- Play the previous track = Reproducir la pista anterior
-- I did not understod the "Inline Song/Artist Label option so I have not translation to it in Spanish

I hope this could be usefull for you, If I find more to translate I will report it to you :smile:

**Comment by me4oslav** [comment]
I have clue how are we supposed to handle the translations. David, do you have any?

**Comment by fossfreedom** [comment]
We need a platform where people can contribute the translation strings.

For CoverArt Browser I use launchpad ... primarily because that is the only user contribution based-translation system I know of - I come from a ubuntu background as you know.

How does Ozon/Numix intend to deal with translations - do you use bugzilla or something like Transifex?

In terms of what I need to do to support translations - that is very straight forward - I just need to copy the translation stuff from CoverArt Browser and generate a POT file and upload this to a translation system.

**Comment by sergioad** [comment]
WOOOW so it is possible? cool, this could be really awesome @fossfreedom :smile: also I have adviced and I quote "If I find more to translate I will report it to you :smile:" so here are two more translations to Spanish

1.- Repeat the current track = Repetir la pista actual
2.- Play the tracks in random order = Reproducir las pistas en orden aleatorio

**Comment by me4oslav** [comment]
David, I think we can use Launchpad's Rosetta for translations.
I also have heavy Ubuntu (even somewhat Canonical) background, so I am quite famiar with Launchpad.

**Comment by fossfreedom** [comment]
ok - I'll take @sergioad translation strings (thanks @sergioad !) and test that the plugin is displaying the translation strings correctly.

Then I'll create a project on launchpad over the weekend.  @sergioad - if you are willing to help - I'll drop a comment here and I'll ask you to test out the launchpad translation system before we open this up to the wider community.

**Comment by sergioad** [comment]
@fossfreedom Unfortunelly I am not familiar with Launchpad, it is very rudimentary for me :smile: also I have probided the major part of the translation :smile:

**Comment by sergioad** [comment]
Some improvements for it, please push them :smile: 

Show or hide the tooltips for the playback controls = Mostrar o ocultar los cosejos para los controles de reproducción
Show or hide volume control = Mostrar o ocultar el control de volumen
Show = Mostrar
Toolbar = Barra de herramientas
Alternative toolbar = Barra de herramientas alternativa
Restart the player for the changes to take effect = Reinicia el reproductor para que los cambios tengan efecto
Playlists = Listas de reproducción
Local collection = Colección local
Other sources = Otras fuentes
Browse = Navegar
Online sources = Fuentes en linea
Configure plugins = Configurar complementos
My top rated = Mis mejores calificador but use Mejores calificados (for more consistency)
Stations = Estaciones
Recently played = Reproducido recientemente
Recently added = añadido recientemente
Import = Importar
View all = Ver todos (if is masculine) or Ver todas (if is femenine)
environments like Gnome and Elementary = entornos como Gnome o Elementary

And finaly a little modification to the UI element "modern"
Modern = Moderna (this change was made because we are refering to the toolbar wich is a reference femenine word, on Spanish is la barra de herramientas (the toolbar)

**Comment by me4oslav** [comment]
Sergio, I think both me and David can guide you though using Launchpad's translation mechanism. It is really easy to work with it.

**Comment by sergioad** [comment]
Realy? cool :smile: BTW I would ike to see my recent update on the po file, this will make the work even easier and will make the ES translations progress quicker and more compete :smile:

**Comment by me4oslav** [comment]
Lets have David first set up a Launchpad account and translation for the plugin and they you can incorporate any changes directly via Launchpad's Rosetta (its translation mechanism).

**Comment by fossfreedom** [comment]
@sergioad 

thanks - looking good :)

![pic](http://i.imgur.com/Yk3Wn0a.png)

**Comment by me4oslav** [comment]
I just noticed that the three automatically generated playlists labels and the "inline song/artist label" are not translated, though. But these are minor details.

**Comment by sergioad** [comment]
WOOOOOOOOW it is looking really good @fossfreedom :+1:,  love the general look, @me4oslav I have not a good English so I can not translate it completelly :cry: , anyway I will promote it's translation :smile:

**Comment by me4oslav** [comment]
Sergio, no worries, people are entitled to be perfect in English. :)
When it gets a LP project with translation mechanism I can translate it in Bulgarian.

**Comment by fossfreedom** [comment]
@sergioad 

  please can you test something for me

Please can you run rhythmbox from a terminal with the following command

    rhythmbox --disable-plugins

This should start rhythmbox with no plugins loaded.

For the playlists - do you see the english "My Top Rated", "Recently added" & "Recently played" or do you see the spanish translations?

**Comment by sergioad** [comment]
Let me see :smile:

**Comment by sergioad** [comment]
@fossfreedom it uses Spanish translations, even with the alternative toolbar plugin enabled

**Comment by fossfreedom** [comment]
ok thanks.

**Comment by sergioad** [comment]
You are wellcome, this could be an issue with the translations or maybe you should remove the EN and ES translations of these sidebar elements

**Comment by fossfreedom** [comment]
@sergioad - not sure.  When I run rhythmbox using:

    LANGUAGE=es_ES.UTF-8
    LANG=es_ES.UTF-8

    rhythmbox --disable-plugins

My rhythmbox starts in spanish - but those 3 playlists are displayed in english.  Maybe this is a rhythmbox 3.2 issue.  What version of rhythmbox are you running?

**Comment by sergioad** [comment]
Let me see

**Comment by sergioad** [comment]
3.2.1

**Comment by fossfreedom** [comment]
@sergioad 

  our launchpad translation website is now up and running.  

Let me quickly talk you through this.

1. The translation website is here: https://translations.launchpad.net/alternative-toolbar
2. Register an account with Launchpad (top right of the screen is a login/register link)
3. Then look at the preferred languages link bottom right of the website above and choose Spanish
4. Click on the spanish translation - you will all the translations - english - spanish and a box where you can submit new translations
5. Click on the drop "Translating" - and change the option from "All Items" to "Untranslated Items".  This is used so that you can just concentrate on strings that have not yet been translated.

Many thanks for any help you can provide.  Ping me here and I'll copy any new translations back to the project here on GitHub.

BTW - your current excellent work is now in the master branch, so you can redownload and install alternative-toolbar and see rhythmbox+alternative in spanish.

**Comment by me4oslav** [comment]
Also - https://plus.google.com/b/114059589828649263886/+Ozonosproject/posts/HBEjjyzBqbL

**Comment by sergioad** [comment]
Thank you every body :smile:

**Comment by me4oslav** [comment]
Right, do we need this issue still open?

**Comment by sergioad** [comment]
how can I appy the translations?

**Comment by fossfreedom** [comment]
@sergioad 

  just git clone the project and install via ./install.sh as per the README file

The ./install.sh script will install your translation in /usr/share/locale/es_ES/LC_MESSAGES 

where es_ES is your locale

**Comment by DreaminginCodeZH** [comment]
/ping @fossfreedom 

I've just finished translating zh_CN, please copy it back to GitHub.

BTW, thank you very much for this plugin, it is a fantastic improvement for us Rhythmbox users!

**Comment by fossfreedom** [comment]
@DreaminginCodeZH many thanks for your contribution - updated!

**Comment by iEFdev** [comment]
I can help you with the Swedish translation. I think I have one completed that I fixed when I installed it on my nephews computers.
 

> “@fossfreedom: Then I'll create a project on launchpad over the weekend.”

But, is that really needed? The po-files are here… Just to clone/edit and make a PR?

**Comment by fossfreedom** [comment]
@iEFdev I would prefer if you use launchpad to-do the translation - its simpler for me to maintain that way.  If you don't which to create a launchpad account feel  free to-do a PR - I'll push up the updated translation on launchpad manually.

https://translations.launchpad.net/alternative-toolbar

**Comment by iEFdev** [comment]
Ok, Launchpad it is then. 👍  I (think) I may have an account there already.
