### ISSUE TITLE
CSD setup is different than what is showed in the README

### ISSUE THREAD

**Issue by swarnendubiswas** [fossfreedom/alternative-toolbar#46]
I have enabled CSD, but my rhythmbox appearance does not conform to what is show on the README. Instead it looks more like the compact toolbar. 
![screenshot from 2015-05-12 20-16-59](https://cloud.githubusercontent.com/assets/7343807/7601443/08d2767c-f8e4-11e4-9929-3bec227b1cb0.png)

I am using Gnome 3.16.x.

**Comment by fossfreedom** [comment]
Thanks for the screenshot. It looks like you are using an older version of the plugin.  Please reinstall the latest version as per the readme instructions

**Comment by swarnendubiswas** [comment]
Your Github page says v0.10.1. I have installed the plugin via the launchpad ppa (ppa:fossfreedom/rhythmbox-plugins), and my installed version is also at 0.10.1.1. This is what the plugin version shows from the About box:

![screenshot from 2015-05-13 20-06-24](https://cloud.githubusercontent.com/assets/7343807/7623669/9c747ee4-f9ab-11e4-9c4a-f4f316fc3214.png)

This is the plugin preferences dialog.

![screenshot from 2015-05-13 20-07-24](https://cloud.githubusercontent.com/assets/7343807/7623677/b7916764-f9ab-11e4-9371-cad1f6c0d1cf.png)

As you can see, the look and feel differs.

**Comment by fossfreedom** [comment]
the version on launchpad is the same as on github - v0.10.1

I suspect you have a package management issue and you are not picking up updates correctly for quite some time.

what is the output of the following

    sudo apt-get update && sudo apt-get upgrade
    apt-cache show rhythmbox-plugin-alternative-toolbar

**Comment by fossfreedom** [comment]
note - also - what is the output of:

    ls -ld ~/.local/share/rhythmbox/plugins/*

You may have previously installed the first version of the software in the above folder - this would be taking precedence over the package install.  If you have you'll need to remove that local install

    rm -rf ~/.local/share/rhythmbox/plugins/alternative-toolbar

**Comment by swarnendubiswas** [comment]
`apt-cache show rhythmbox-plugin-alternative-toolbar`
Package: rhythmbox-plugin-alternative-toolbar
Priority: extra
Section: misc
Installed-Size: 619
Maintainer: fossfreedom <foss.freedom@gmail.com>
Architecture: all
Version: 0.10.1-1
Depends: dconf-gsettings-backend | gsettings-backend, python3-gi-cairo, rhythmbox
Filename: pool/main/r/rhythmbox-plugin-alternative-toolbar/rhythmbox-plugin-alternative-toolbar_0.10.1-1_all.deb
Size: 64116
MD5sum: 6fc278cd8f2b0335023c37a79f519e13
SHA1: ff00e5ef41802f18c043521899cd163a690f7f42
SHA256: 9ad9c2cc33c31a16450e9d4d35ef4f10c76a6a0777c53b88755b27fc03b90bbf
Description-en: Show or hide the main toolbar for Rhythmbox
Description-md5: f6ba6c494edef235c32ffd9f66fe2621

So apt-cache output seems okay. I think I have an older version installed in `~/.local/share/rhythmbox/plugins/.`. Removing that helps, thanks. Is it not possible for your installer script to automate this fact?

**Comment by fossfreedom** [comment]
Which installer script?

The debian package can never have any knowledge about what is installed on a local account basis.

Some people have very good reasons why they want to override the default package - developing a patch etc.

Anyway - looks like all is well.  I'll close this now.
