### ISSUE TITLE
Alternate Toolbar needs a rename

### ISSUE THREAD

**Issue by HEXcube** [fossfreedom/alternative-toolbar#47]
Though Alternate Toolbar started as a simple plugin to change the toolbar a bit, it has now grown much beyond it's initial goal. In addition to the _toolbar_, the plugin can now change the _sidebar_, _plugins config screen_, _position of progress bar_, _enable CSD_, _compact style_ and more. The plugin has completely overhauled the visual style of Rhythmbox. Since the plugin gave Rhythmbox a total cosmetic redesign, I feel it **needs a rename**.
##

**Comment by fossfreedom** [comment]
Work to be done if this is done:

1. global string search to change alternative-toolbar and alttoolbar references to "x"
2. create a new Debian package called "rhythmbox-plugin-x" and work out how to produce a blank "rhythmbox-plugin-alternative-toolbar" package that is autoinstalled when rhythmbox-plugin-x is installed
3. likewise workout how to migrate users from rhythmbox-plugin-alternative-toolbar to rhythmbox-plugin-x
4. discontinue the translation project on launchpad
5. create a new translation project and reimport all code and translations

cons:
1. The plugin has been heavily promoted by Ozon and major websites  - changing the name will effectively need re-publicizing ... no guarantees that this change will get out and thus people will be confused ... or worse think the project has been discontinued
2. havent a clue how to do 2 & 3 above
3. all in all seems like a lot of work ... and personally I want to work on some rather nice coverart-browser changes

pros:
1. fresh-start - more obvious name
2. can't think of anything else to say

Next steps:
1. agree on a snappy name
2. find someone to help with the debian packaging
3. find the energy and time to do this

**Comment by me4oslav** [comment]
Renaming the plugin as everything out there has pros and cons.

Cons would be:
  -  This name has already became somewhat popular, because of its mentions on the social media (blogs, facebook/twitter/G+ and etc ...);
  -  Logistics - renaming would mean new repos on GtHub and Launchpad for the plugin (or renaming of doable) and changing strings in the UI, which would mean that translators will have to retranslate these strings;

Pros are:
  -  As you said, the plugin's reach extends way beyond the scope of tailoring the toolbars, so it only makes sense that its name and its description are to mirror the new extent of the plugin;
  -  New name would mean a brand new wave of articles and posts about the plugin on the social media;

Overall, this plugin is David's, so @fossfreedom, are you for or against?

**Comment by fossfreedom** [comment]
@me4oslav - I'm not adverse to this ... but there is a but...  it's not a high enough priority right at this moment.

I've got one priority on alternative-toolbar - the repeat one song capability.  Then I want to concentrate on coverart-browser i.e. any tidyups you yourself may suggest, but one key rework which will be the artist-view.

**Comment by me4oslav** [comment]
Yup, I am done with major design work on alternative-toolbar. The last big suggestion was the configure plugins screen, so now I am scratching the surface with coverart. I don't plan to work as much as I did on alternative toolbar more, so if I do any more suggestions about it, they will be minor ones like the about dialog (already fixed) and the graphic setup.

**Comment by HEXcube** [comment]
Wow, that's a lot of cons! I didn't think about the after effects of renaming and the work needed for doing so. It seems the cons beat the pros, atleast for now. And like @fossfreedom said, there are higher priority tasks on the list. Besides, there's a chance that many changes like CSD support, new plugins screen, sidebar, etc may make it into upstream later and the scope of the plugin'll come back to focus on toolbar alone. Or you guys may do more awesome stuff and evolve the plugin further beyond it's current state that renaming'll become a priority. :-) I think this issue should be labelled *wishlist* and considered later when this becomes relevant.

**Comment by me4oslav** [comment]
Alas backporting our changes upstream is much easier said than done.

**Comment by fossfreedom** [comment]
not going to implement this.
