### ISSUE TITLE
Window border & improved screenshots

### ISSUE THREAD

**Issue by julianrichen** [fossfreedom/alternative-toolbar#48]
First off thanks for the plugin, makes RB look much better under gnome. Considering the plugin has gonna over some significant clean-up I figured it might be good to improve the screenshots on the README to reflect that. When taking them (with the gnome-screenshot /w drop shadow) I noticed the windows lack a border. Many of the gnome applications have a light grey border to make the window pop. Is this intentional? Below are some of the screenshots.

Vanilla:
![alternative-toolbar](http://i.imgur.com/CdgG0fl.png)

alternative-toolbar:
![alternative-toolbar](http://i.imgur.com/zc8A3Jm.png)
![alternative-toolbar](http://i.imgur.com/OJqI0ae.png)
![alternative-toolbar](http://i.imgur.com/6L5Nwhi.png)

Notice the white border at the bottom:
![alternative-toolbar](http://i.imgur.com/Ai66NyO.png)
![alternative-toolbar](http://i.imgur.com/mDvAKDZ.png)

Notice that this still has the border:
![alternative-toolbar](http://i.imgur.com/6IZKviP.png)

Which makes it pop over another window:
![alternative-toolbar](http://i.imgur.com/fRL2XzT.png)
![alternative-toolbar](http://i.imgur.com/3U5dFe5.png)
![alternative-toolbar](http://i.imgur.com/ZQBttdN.png)
![alternative-toolbar](http://i.imgur.com/mbrPoUm.png)
![alternative-toolbar](http://i.imgur.com/0uhyaOi.png)

The reason the background window is not grayed out when a window is over it is because I individually overlayed them in GIMP, can't get the clean dropshadow with multiple windows. I'll fix that later plus I wanted to highlight the border issue.

Album version: http://imgur.com/a/IPNPg

I figured I would bring this up before doing a pull request with the new images, that is of course if you want them.

**Comment by fossfreedom** [comment]
thanks - which version of Rhythmbox have you taken the pictures with?

Which version of GTK+ are you using?

If you take a screenshot of another CSD based app do you have the left-top border still?

**Comment by julianrichen** [comment]
> thanks - which version of Rhythmbox have you taken the pictures with?

3.2.1

> Which version of GTK+ are you using?

I believe this will do it?
```
julian@octus:~$ dpkg -s libgtk-3-0|grep '^Version'
Version: 3.14.5-1
```

> If you take a screenshot of another CSD based app do you have the left-top border still?

I'm not 100% how to check this but I assume Gnome Files/Nautilus is CSD? If so then no, it does not have a border:
![Uploading Screenshot from 2015-05-23 13:06:35.png…]()

**Comment by fossfreedom** [comment]
yep - looks very much like CSD is changing the border - looks like its intentional given that Files (which is indeed a CSD based app) is behaving the same as RB + Alternative Toolbar.

Every GTK version seems to change something in this area.  It would be interesting to see what happens under GTK+3.16.

Anyway - yes, feel free to improve the README - maybe some smaller screenshots showing the additional functionality such as Repeat Current Track, Music Seek etc etc.

**Comment by me4oslav** [comment]
@julianrichen Aye, do make a pull request with nicer screenshots for the readme. Would definitely be most welcome.

**Comment by julianrichen** [comment]
Would you prefer something like this:
![](http://i.imgur.com/bB6ZII5.png)

Or something like this?
![](http://i.imgur.com/rMkxjxw.png)

Also for future reference when you want to take a screenshot with Gnome-screenshot and the application is CSD un-check the "Include the window border" option and make sure no effect is applied. It will automaticlly include a border with a shadow around it.

If the application is not CSD the "Include the window border" and "apply effect" are needed to acheive the same results.

Kind of misleading.

**Comment by me4oslav** [comment]
I have an idea about the readme. Will write it down in the morning.

**Comment by julianrichen** [comment]
Updated the screenshots & played around a little with the formating: [julianrichen/alternative-toolbar/readme](https://github.com/julianrichen/alternative-toolbar/tree/readme) (they are split into separate commits).

**Comment by me4oslav** [comment]
@julianrichen, good job!
Just mention that for Ubuntu and derivates there is a PPA* and add the instructions for installing from it.
* PPA link - https://launchpad.net/~fossfreedom/+archive/ubuntu/rhythmbox-plugins
