### ISSUE TITLE
can't drag & drop songs to media player in enhanced sidebar

### ISSUE THREAD

**Issue by kppmsd** [fossfreedom/alternative-toolbar#49]
first of all thanks for all your work on this plugin. finally found a media player I like :)

However I've noticed some missing functionality when using the plugin with 'enhanced sidebar' enabled.

Without 'enhanced sidebar' enabled, you can add songs to your attached portable media player, by dragging and dropping songs from your library on to the media player icon on the sidebar.

With enhanced sidebar, dragging and dropping is simply not possible.

If i'm not mistaken, drag & drop is the only possible way to add songs to portable players in rhythmbox, so some users may need to keep the nicer sidebar disabled because of this.

**Comment by me4oslav** [comment]
This is definitely greenlit from the design side.
Now it is up to @fossfreedom to doan implementation.

**Comment by fossfreedom** [comment]
@kppmsd - in the interim try copy and paste 

i.e. - ctrl+ click your tracks you want to copy.  Right click and choose copy.

Then navigate to your playlist or portable player and click on the area that contains the playlist/portable player list of songs.  CTRL+V to paste.

**Comment by kppmsd** [comment]
@fossfreedom thanks for that. I knew there had to be another way :)

IMHO, adding songs via drag&drop is something users still would expect since it supported in default rhythmbox GUI.

Also this seems to effect other sidebar panes than media players. For example you should also be able to drag&drop songs to playlists in sidebar, but it seems that drag&dropping anywhere in the new sidebar is impossible.

**Comment by fossfreedom** [comment]
@kppmsd 

  the commits above adds drag-drop support onto the sidebar.  I've tested this with the play queue & playlists by dragging tracks/albums/genres from the Music Library source

  Please can you also test this for me and let me know your thoughts?

TIA

**Comment by kppmsd** [comment]
Updated to commit 7092a6c, dragging and dropping songs to play queue and playlists works fine.

Drag&dropping songs to my ipod still doesn't seem to work though: the iPod pane in side panel accepts drag&dropping now, but songs simply don't get transferred to the player.

Apart from that, I think there could be some sort of highlight in the sidebar item when you drag songs on it, just like the old sidebar does:
![screenshot from 2015-05-27 11-38-28](https://cloud.githubusercontent.com/assets/12579617/7832410/9313c294-0467-11e5-8ddb-15b1608800e8.png)
(I'm draggin a song on the ipod item there, couldn't figure out how to capture mouse pointer in screenshot with gnome-shell)

**Comment by fossfreedom** [comment]
Does the mouse pointer change to indicate that a drop is possible? If yes, does holding the mouse over the iPod whilst dropping for a couple of seconds switch to the iPod source? You should be able then to drop into the existing iPod song list view
On 27 May 2015 10:06, kppmsd <notifications@github.com> wrote:Updated to commit 7092a6c, dragging and dropping songs to play queue and playlists works fine.

Drag&dropping songs to my ipod still doesn't seem to work though: the iPod pane in side panel accepts drag&dropping now, but songs simply don't get transferred to the player.

Apart from that, I think there could be some sort of highlight in the sidebar item when you drag songs on it, just like the old sidebar does:

(I'm draggin a song on the ipod item there, couldn't figure out how to capture mouse pointer in screenshot with gnome-shell)

**Comment by fossfreedom** [comment]
@kppmsd 

  I'm hoping that the above commit now correctly initiates a transfer to portable devices ...

please can you let me know if this resolves the dropping issue onto your ipod?

I'll look into this highlighting issue later

**Comment by kppmsd** [comment]
commit 33c81cf enables transferrings songs to my player via drag & dropping songs on the sidebar item.

to answer your earlier question, mouse pointer did and still does change to indicate that drop is possible. Also holding the mouse over the sidebar item switches to ipod source.

However, dropping the dragged song(s) to the ipod playlist view still doesn't transfer songs to the device, even after the latest commit that fixed d&d to the sidebar. It's not an issue for me, but I thought you should know.

Thanks for sorting out this issue so quickly :)
I'll still be watching this issue in case you need any more help with testing

**Comment by kppmsd** [comment]
I also noticed a small issue with commit c13418f

There are now highlights in above and below every sidebar item that accepts dropping to, when you move your mouse cursor in between the items.

I'm not sure if this depends on the theme used so here's another screenshot:
![untitled](https://cloud.githubusercontent.com/assets/12579617/7848800/bc4a653a-04d7-11e5-86e0-57d4a431f026.png)
also, this doesn't happen if enhanced sidebar is disabled.

Apart from that, the d&d highlight looks good to me :)

**Comment by fossfreedom** [comment]
@kppmsd 

  the above commit hides the between D&D line.

BTW - I dont own an Ipod hence working a bit blind here.

Did the old sidebar support dropping onto the ipod playlist itself - or did you only have the ability to transfer songs via dropping onto the sidebar?

**Comment by kppmsd** [comment]
Apparently drag&dropping songs to the ipod playlist view doesn't work with the old sidebar either, or even if I disable alternative-toolbar plugin completely. Sorry, I should have thought of checking that earlier.

Also, the line between d&d sidebar items is now gone with the latest commit.

Everything seems to be in order now regarding d&d, so I'm going to close this issue.
Thanks again for sorting it out :)

**Comment by fossfreedom** [comment]
excellent - you are most welcome!
