### ISSUE TITLE
Is there a point of the volume button?

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#5]
So, I've been thinking - I am pretty sure that most desktop environments out there has a volume control. This might actually be true for all DEs. And I am 100% sure that all DEs that support CSD have a colume control on their panel. This makes me wonder - is the volume button on the headerbar really needed?
The way I see it:
A) Creates clutter, because it is an extra UI element;
B) Dublicates the system volume control, which creates confusion in the users;
Hence I am suggesting removing it or making it optional, but disabled out of the box.
I've attached a screenie of the issue.
![screenshot from 2015-03-14 16 29 24](https://cloud.githubusercontent.com/assets/1658870/6652041/4180f6d8-ca68-11e4-9090-ef4ef03d6aab.png)

**Comment by me4oslav** [comment]
Why can't I add "enhancement" tag?

**Comment by me4oslav** [comment]
This concern (quoting):
"Sometimes you want to only lower the music sound and not other sounds on your computer. Example: you are listening to music, you get a call on your phone,you lower the music volume. Other sounds like Skype call notifs are still loud . well I can't explain well enough.﻿ And listening to light music while watching some youtube.﻿" has been raised.
I suppose it would be safer to leave it as option that can be enabled.

**Comment by knight-corvi** [comment]
I'm also with the idea of leaving the volume button. As an option, I think changing the postion of the volume button somewhere else would be better than removing it.

**Comment by me4oslav** [comment]
I did say "I suppose it would be safer to leave it as option that can be enabled." which I think solves the issue.

**Comment by fossfreedom** [comment]
yep - happy to make it an option, enabled via the plugin preferences.

**Comment by me4oslav** [comment]
YAY. There are more things we can do (improve) about the CSD and after it is done, we can go even further than the headerbar with polishing the UI if you wish. I can help with the design and I rhink i can bring one more designer to help too. That is providing you're willing to further.
What do you say?

**Comment by knight-corvi** [comment]
my concern to be an enable/disable option is that someone might not be aware of the option, but then again I guess people will look for it if need. The idea of the replacing the sound button came from where spotify has a volume slider on the bottom of the player.
![screenshot from 2015-03-14 09 00 17](https://cloud.githubusercontent.com/assets/3454040/6652480/6052a510-ca2d-11e4-9a0d-860ce2c65413.png)

**Comment by fossfreedom** [comment]
@me4oslav 

  :) nice to get some feedback.  Create new a general discussion issue or individual issues.

Just to say - graphical design is not my strong point - I'm more of a code hacker.  Thus - would be very welcome to work with your goodself or others to improve stuff.

**Comment by me4oslav** [comment]
@fossfreedom I will.
BTW, fwiw this is UI/UX design, not graphic one. :)
Oh and if this is expanding beyond the scope of CSD headerbar shouldn't the repo get new name?

**Comment by fossfreedom** [comment]
@me4oslav 

  if any suggestions are going beyond the plugins remit, don't worry I'll be shouting :)

Where possible the code changes should & will be applicable to all desktop-environments - not just for CSD orientated DEs such as gnome-shell and projects like Ozon.

The above commit deals with the optional volume control - tested across CSD, compact toolbar as well as RB's standard toolbar.

**Comment by me4oslav** [comment]
Works fine. I will create separate issues with with more CSD improvements.
I do plan to go above CSD scope with UI improvements, but I don't think that will go above the scope of plugins.
