### ISSUE TITLE
plugins window icons need a tootips

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#50]
from a G+ comment from @HEXcube, plugin icon toolbar need tooltips.

If we are a bit clever (dangerous I know) - we could reuse the rhythmbox strings so that we don't need to add more translation strings to launchpad.

Thus tooltips will use 
 - "_Preferences"
- "_About"
- "_Help"

Need to remember to remove _ chars as well as any strings such as (_x) from translated strings

**Comment by me4oslav** [comment]
Aye, tooltips would definitely be nice. Even nicer if we reuse the strings.

**Comment by me4oslav** [comment]
Oh, I just pulled and compiled the latest master and the tooltips are there. Should the issue stay open?

**Comment by fossfreedom** [comment]
Needs a bit of testing with various languages e.g. Chinese which we  have a translation for together with languages such as Russian which we don't have but rhythmbox does

**Comment by me4oslav** [comment]
Ah. Is it possible to just install a bunch of i18n packages and start Rhythmbox with these locales?

**Comment by fossfreedom** [comment]
Yep ... Should work that way .. In the past iI've tested a Spanish locale that way (install language support in system settings Ubuntu)

**Comment by me4oslav** [comment]
What was the command for starting with different locale?
And yes, installing additional locales is incredibly easy in Gnome.

**Comment by fossfreedom** [comment]
LANG=en_GB.utf8
LANGUAGE=en_GB.utf8
rhythm box

The above will use the British locale

**Comment by me4oslav** [comment]
The moment when I use the UK locale out of the box ... :)
I will install Russian and test with it.
And will also do some coverart work.

**Comment by me4oslav** [comment]
There, did some CA design work - https://github.com/fossfreedom/coverart-browser/issues/363

**Comment by HEXcube** [comment]
Tested the the new version 0.11.1 of _alternative-toolbar_ from PPA. With the tooltip issue fixed, icons on the Plugin Selection window aren't confusing anymore! :-)
![preferences button](https://cloud.githubusercontent.com/assets/3755396/7833784/0a251d6e-0487-11e5-82d8-5d617645bdae.png) ![about button](https://cloud.githubusercontent.com/assets/3755396/7833792/141f4baa-0487-11e5-8139-817c7602f9af.png) ![help button](https://cloud.githubusercontent.com/assets/3755396/7833793/1a45cd06-0487-11e5-91de-1c5cee4cf029.png)

**Comment by me4oslav** [comment]
We just need to check with a different locale.

**Comment by fossfreedom** [comment]
tested with spanish and chinese.  All looks ok ... not that I actually understood what I was seeing!

**Comment by me4oslav** [comment]
Molto bene. :P
