### ISSUE TITLE
Alternative Toolbar plugin causes application volume level to lower on each startup if not maxed

### ISSUE THREAD

**Issue by nekohayo** [fossfreedom/alternative-toolbar#51]
If this plugin is activated, and if Rhythmbox's volume was not left at 100%, on each subsequent start of the application, the volume will be lower.

This can be seen by opening gnome-control-center's volume settings, going to the Applications tab, setting rhythmbox's volume slider slightly below 100%, then restarting rhythmbox a few times.

This is with GNOME 3.14, RB 3.1 and plugin version da08d53

**Comment by fossfreedom** [comment]
Hi,

  thanks for the report.  

Please can you checkout the latest code and let me know if this is now resolved?

**Comment by nekohayo** [comment]
Yep, that fixed it!
