### ISSUE TITLE
Save title or category setting after restart

### ISSUE THREAD

**Issue by jano-on-github** [fossfreedom/alternative-toolbar#53]
Thanks for the great work, I just found one thing a bit annoying: When I switch on CSD I want the default view to stay on 'category' but it always switches back to 'title' after a restart of rhythmbox. Im using it on elementaryOS Freya with rhythmbox 3.2

**Comment by fossfreedom** [comment]
@jano-on-github 

  think the above commit should fix this.

Please let me know if you have any adverse issues with this change.

cheers
