### ISSUE TITLE
remember Show source toolbar setting between sessions

### ISSUE THREAD

**Issue by MichaelTiebesl** [fossfreedom/alternative-toolbar#55]
Is it possible to have the Source Toolbar disabled?
I have to disable it with Ctrl+T when i start up Rhythmbox.
There is an option in the menu but it is only working until i close Rhythmbox.

Thanks

**Comment by fossfreedom** [comment]
what is your RB version?

Are you using standard menu/compact menu or client-side-decorated?

What desktop environment are you using - linux version?

**Comment by MichaelTiebesl** [comment]
Sorry i forgot to put info about it. I know how annoying that can be.

Ubuntu 15.04  Rhythmbox 3.2.1 (PPA) 
Side panel is standard disabled with me.
See attached picture for settings.

![menu](https://cloud.githubusercontent.com/assets/10792019/8610814/d61d534e-26e9-11e5-95fa-4a7b7eb89055.png)

**Comment by fossfreedom** [comment]
@MichaelTiebesl 

  the above commit should add this capability for standard and compact toolbars.

Shout if you have any issues.

cheers.

**Comment by MichaelTiebesl** [comment]
Thanks for your time. It works for me.
