### ISSUE TITLE
Rhythmbox does not follow the locale formats when using this plugin

### ISSUE THREAD

**Issue by archdria** [fossfreedom/alternative-toolbar#56]
I am using a 24 hour format, and when this plugin is enabled, the format is always set to AM/PM.

**Comment by fossfreedom** [comment]
how do you set "24 hour format"?  Not sure I understand why the locale format is needed here.

The format being displayed is "progress time / track duration" where both time values are minute:second format

**Comment by archdria** [comment]
Oh, sorry I misexplained myself.
I go to gnome-system-settings -> Date & Time -> Time Format -> then set it to 24h.
GNOME applications like Nautilus, show the created/modified times using this format.
However, when using this plugin, Rhythmbox shows the Last Played and Date Added times in the AM/PM format.
Disabling the plugin makes Rhythmbox follow the time format defined in gnome-system-settings.

**Comment by fossfreedom** [comment]
any chance of a screenshot?

**Comment by archdria** [comment]
In the screenshot you can see how the *Time Format* has been set to *24-hour*.
*GNOME Shell* displays the time using this format
*Nautilus* is also showing the *Modified* times for some files using this format.
Finally, *Rhythmbox* is showing *Last Played* and *Date Added* times using the *AM/PM Format*.
![screenshot from 2015-07-17 16-02-34](https://cloud.githubusercontent.com/assets/1671644/8748857/8e940e64-2c9d-11e5-8f26-b998644ba046.png)

**Comment by fossfreedom** [comment]
hmm - very strange behaviour.  I'm not changing or applying any time locale stuff within the plugin.

I'll try later to see if I can reproduce.  Please can you let me know what version of rhythmbox you are using and what distro you are using - if you are using ubuntu are you using any gnome PPA ?

**Comment by archdria** [comment]
Yes, I agree, quite strange, I've been using your plugin for some weeks now and I realised this just yesterday...

I am on Arch Linux, using Rhythmbox 3.2.1 from the official repos.
Thank you :)

**Comment by fossfreedom** [comment]
quick update.

I've tried on ubuntu unity 14.04 - gtk+3.10 - time stays 24hr format.

I've tried on ubuntu gnome-shell 15.10 - gtk+3.16 - time stays 24hr format.

In-fact - the date and time screen format doesnt appear to affect the format in nautilus or rhythmbox - it always stays 24hr format.  Changing the time format only changes the time format in the gnome-shell panel.

**Comment by archdria** [comment]
I have noticed that this bug only appears if you disable the enhanced toolbar (I had it disabled because it doesn't show missing elements when you erase them from the library).
Can you confirm that?

**Comment by fossfreedom** [comment]
ok - have now reproduced this on unity.

You need to have the enhanced plugins dialogue enabled.

Restart rhythmbox - everything is ok.  As soon as you go into the plugins window, the time in the column changes and doesnt change back when you close the dialog.

If you do not use the enhanced plugins dialogue the problem doesnt occur.

I'll have a closer look at the enhanced plugins dialogue window.

**Comment by fossfreedom** [comment]
@archdria 

  think the above commit fixes this.  

Please let me know.  TIA

**Comment by archdria** [comment]
Hmm, I am still able to reproduce if I have the plugin enabled and one or none of the following enabled:
- enhanced plug-ins dialogue
- enhanced sidebar

If I enable both, the locale it's OK

**Comment by fossfreedom** [comment]
Sorry then.  No idea.

Works for me on both ubuntu desktop environments and GTK+ versions.

**Comment by fossfreedom** [comment]
@archdria 

  one more try - this one I'm working blind since as I said  that I cannot reproduce.

Try pulling the latest sources to see if the above commit fixes this.

**Comment by archdria** [comment]
Yes! You have the gift of blind bug-fixing!
Thank you!
