### ISSUE TITLE
Missing files in the enhanced toolbar

### ISSUE THREAD

**Issue by archdria** [fossfreedom/alternative-toolbar#59]
Whenever a file disappears from the music collection, Rhythmbox creates an entry on the sidebar, named 'Missing files', so that you can keep track of what happens and make sure all your music is still there if this entry does not appear.

However, this feature is lost with alternative-toolbar's enhanced sidebar.
Could it be possible to have it back?

Thank you :)

**Comment by MichaelTiebesl** [comment]
For me it is still there i see. I use Ubuntu 15.04 with Rhythmbox 3.2.1

**Comment by fossfreedom** [comment]
thanks @MichaelTiebesl - similar here - I see this working also.

@archdria - what distro are you using - what version of Rhythmbox?

What version of the plugin are you running?  - have a look at the about button in the plugins window.

what is the contents of the file x.output produced by the following command when running with the enhanced sidebar?

    rhythmbox -D alternative > x.output 2>&1

Next run the following with the enhanced sidebar turned off i.e. showing the missing files option.

    rhythmbox -D alternative > x2.output 2>&1

**Comment by archdria** [comment]
Hi, I'm running rhythmbox from master and the latest version of the plugin on Arch Linux.
The missing files entry only appears the second time rhytmbox is started after the files have been deleted. The way to reproduce is:
1. erase some library files on nautilus
2. start rhythmbox (nothing appears, but I see how the number of songs decreases)
3. restart rhythmbox (now it appears)

Can you confirm this behaviour?
Thank you :)

**Comment by fossfreedom** [comment]
@archdria - thanks.  

Yes I can confirm your observation.

I've looked more closely at rhythmbox does and it appears at first glance that there doesnt appear to be any event emitted when "missing files" is inserted into the tree-view when a track is removed... so there is nothing I can use to refresh the enhanced tree-view.

This will need a more in-depth look at some point.

**Comment by benjaoming** [comment]
Wow, this plugin is really insane :) Big props!

I tried to reproduce this issue, and I can confirm it using RB 3.0.2:

Without alternate toolbar: No issue, Missing Files shows up upon first restart.
With alternate toolbar: Yup, confirming that Missing Files entry is not there.

**Comment by fossfreedom** [comment]
Yep,

  The code is here - https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_sidebar.py

The connect_signals connects to the RB.RhythmDBModel events so that whenever rhythmbox updates the "now hidden" source treeview, in alternative-toolbar we respond to those updates to reflect the changes to the new enhanced sidebar treeview.

What is happening is that Rhythmbox is not sending a RB.RhythmDBModel signal for missing files.

What I suspect needs doing is to also monitor the "now hidden" treeview insert/change/delete events as well and see if the missing files treeview entry is created/changed/deleted (it must be sent since GTK should do this automatically).

**Comment by benjaoming** [comment]
Could the signal be sent before the plugin is initialized and listening?

**Comment by fossfreedom** [comment]
doubtful - I've seen the missing files "appear" a few seconds after rhythmbox is fully up.  There is more than enough time for the plugin to startup and listen.

I suppose adding a connect-insert type signal to the tree view and "print"ing what appears on the event will verify/dismiss what I have hypothesized.

**Comment by fossfreedom** [comment]
note to self - same issue with "Import Errors"  - this is also not seen

**Comment by fossfreedom** [comment]
@archdria and @benjaoming - I think this is now resolved.  I would appreciate it if you have some time to  install this from git and let me know if there are any adverse changes to what I have done.

cheers.

**Comment by archdria** [comment]
Hi! I've just tried now, and the problem seems solved: files missing appear after the first start and not the second.

Thank you very much! Keep up with the good work on this amazing plugin!
