### ISSUE TITLE
Black bars around Rhythmbox in Ubuntu 15.10

### ISSUE THREAD

**Issue by elmagio** [fossfreedom/alternative-toolbar#62]
When using the modern interface in Ubuntu 15.10 on Unity, the window is surounded by black bars. It works well without the modern interface but with compact controls, and worked well in Unity on Ubuntu 15.04 too.

Attached below is a screenshot of the issue.

![image](https://cloud.githubusercontent.com/assets/14126056/10921900/7717a148-8278-11e5-8482-4f228c6bdb29.png)

**Comment by fossfreedom** [comment]
I've tested on the default gnome-shell theme adwaita and there are no black borders - just the standard stylish adwaita shadow.

What theme is that?

Are there any other headerbar based applications that show that problem?

**Comment by elmagio** [comment]
The theme is Arc, by horst3180.

Didn't think it could come from that, but after testing with other GTK themes it appears that it does. I think it has to do with the fact that this theme has transparency in some places.

But no, up until now I haven't seen any other app showing this behaviour even with that theme.

**Comment by fossfreedom** [comment]
interesting.

I used these instructions to install the arc-theme on 15.10

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/arc-theme.list"
sudo apt-get update
sudo apt-get install arc-theme

I then used unity-tweak-tool to change to each of the three arc themes.  None showed the black borders

**Comment by elmagio** [comment]
Nevermind, I know what I did wrong now... Apparently after upgrading to Ubuntu 15.10 I stayed on the 15.04 release of the Arc theme, which is what caused the issue.

Switched repositories now and everything is working as intended now.

Sorry for the bother and thanks for the help !
