### ISSUE TITLE
Edit/Extract/Eject/... toolbar hidden in Audio-CD view

### ISSUE THREAD

**Issue by fin-ger** [fossfreedom/alternative-toolbar#66]
When alternative toolbar plugin is enabled, the toolbar for extracting an audio-cd to the library is hidden. 

![rhythmbox_1](https://cloud.githubusercontent.com/assets/5300274/12002712/6ebf2d56-ab07-11e5-8cce-e48deba41a09.png)

![rhythmbox_2](https://cloud.githubusercontent.com/assets/5300274/12002716/83259fbe-ab07-11e5-8fad-fa5ea12b34ea.png)

**Comment by fossfreedom** [comment]
Ctrl + T should display the source toolbar ... Is that not working on this source?

**Comment by fin-ger** [comment]
Ah thanks, it's working.
