### ISSUE TITLE
add support to reorder columns

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/alternative-toolbar#67]
One oft issue that is repeatedly brought up is the inability to reorder columns by dragging the header.

I've looked into this and it looks like it is certainly possible to add this capability - some internal experimental code has shown this.

Need to think through how this should work in practise where different views show the same columns, some other views have very different views.  How do we say "this view is the same as something else" when a view has been altered.

Need also to think through how to remember column changes between rhythmbox restarts.

**Comment by Zomtir** [comment]
Thanks for referencing the bug report! I discovered this plugin thereby.

Note that the column changes don't sync between the playlists and/or reset when switching view, too.

**Comment by fossfreedom** [comment]
hmm - sync'ing between static playlists work for me.  Sync'ing between automatic playlists also work.  There is no attempt to sync between static & automatic playlists ... see below.

Note - all views are individual - it is deliberate to not try and sync between views - for example

in library view the title, artist and album are important for me so I pull them together - whereas on the play-queue I'm most interested in the title, album and rating.
