### ISSUE TITLE
The repeat and shuffle buttons do not work?

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#7]
This might not be an issue and be because I am stupid and am still a rookie in RB-ville.
![screenshot from 2015-03-14 21 26 46](https://cloud.githubusercontent.com/assets/1658870/6653211/dde1f464-ca90-11e4-8214-8b67e466a64a.png)

**Comment by fossfreedom** [comment]
hmm.

which distro are you using.  Works here on ubuntu 14.04, Gtk 3.10, RB 3.1,  on both Unity and Gnome-Shell

also tested on ubuntu 15.04, GTK 3.14, RB3.1, Unity and Gnome-Shell

**Comment by me4oslav** [comment]
Fedora 21.

**Comment by knight-corvi** [comment]
same here. arch, gtk 3.14, gnome-shell. RB 3.1 as well

**Comment by fossfreedom** [comment]
... dislike distro specific issues :(

downloading fedora 21 - last time I tried fedora it took me 3 days to set up because the installer was terrible and yum wasnt much better.

This may take some time...

**Comment by me4oslav** [comment]
just install rhythmbox from gnome-software. It is very easy. :)

**Comment by fossfreedom** [comment]
ok ... the installer is just as bad as I remembered it!

other than that - yum actually worked this time around - still slow ...

The last commit should fix this

**Comment by me4oslav** [comment]
It does. Good job!
