### ISSUE TITLE
Column Order Doesn't Save

### ISSUE THREAD

**Issue by jdorenbush** [fossfreedom/alternative-toolbar#73]
Changes to the column order don't survive after closing Rhythmbox. The order gets reset to the default position.

Note: I noticed that the order is preserved through the player Restart process via the plugin's preferences dialog.

Rhythmbox 3.2.1
Alternative Toolbar 0.16.0

**Comment by fossfreedom** [comment]
Hi,

  how are you closing rhythmbox - via the "x" window button - or via File - Quit?

**Comment by jdorenbush** [comment]
Just tested both ways, here's the results...
* Clicking "x" preserves column order
* Selecting "Close" from the File menu resets column order to default
  * Using the keyboard shortcut (Ctrl+W) for Close has the same outcome

**Comment by fossfreedom** [comment]
thanks.

  The code in this area is a bit of a hack - the problem being is that by enabling the drag-drop "change" event to allow you to drag-drop the column whenever a column is deleted, the event is fired automatically by GTK.

When closing - rhythmbox deletes columns... and thus fires the drag-drop changing event automatically.  I thought I hacked around this ... but looks like I didnt catch the File Close method.

I'm going to have to think of something smarter.  I'll let you know.  In the interim ... remember to press the "x" button :)

**Comment by fossfreedom** [comment]
Hi - the PPA has been updated with v0.16.2 - the above commit should fix this.

**Comment by jdorenbush** [comment]
Confirming this is fixed now.

*PS: The lack of built-in support to reorder columns baffles me. This is the single reason why I haven't switched from Banshee to Rhythmbox. Now, thanks to your plugin, I can finally make the switch. Thank you!*
