### ISSUE TITLE
Search Doesn't Always Work

### ISSUE THREAD

**Issue by djh101** [fossfreedom/alternative-toolbar#75]
The search feature doesn't always work. I think it would be better if there was an option to keep the original search mechanism instead of the Ctrl+F search.

**Comment by fossfreedom** [comment]
Thanks for raising the issue.

  I need a bit more information to help.  Can you pin down when searching doesnt work?  What were you doing - which view etc.  Basically - I need enough info to reproduce your issue.

What do you mean by the "original search mechanism" ?

Suggest use the compact toolbar not the "modern" header bar style and leave the view source bar always visible (CTRL + T)

**Comment by djh101** [comment]
Ah, I did not know about CTRL+T. It seems I may have reported this bug without really testing it enough. Search works fine as long as the song list is focused. When it doesn't seem to work is after you select something from another menu (e.g. the playlist or column browser menu).

Thank you.

**Comment by fossfreedom** [comment]
I've made some tweaks in another issue to get CTRL+F to toggle the search button on & off.

I cannot reproduce your issue though :(

Can you install the latest code and see if my tweak helps in anyway?

**Comment by djh101** [comment]
Sorry for the late response.

By original search mechanism, I meant the source toolbar search box that comes with Rhythmbox (versus the pop-up search included with the alternative toolbar which functions somewhat differently).

Now that I know I can continue to use the fixed source toolbar search instead of the popup, I don't have anymore issues. In case anyone else is having trouble with the enhanced searching, though, here's a summary of how it works for me:
-If the song list is focused (e.g. after you click on a song), then typing into the Ctrl + F search box will take you to the first song whose artist name contains the search text.
-If the category list is focused (e.g. after you click on an artist name), then the search box will center the first artist/album/genre containing the search text.
-Same thing for the playlist menu.

I assume this is how the search feature is supposed to function. However, being used to the classic search feature, I had initially expected the search box to always search through the library for songs containing the search text (instead of search through whatever panel is in focus).

**Comment by fossfreedom** [comment]
if you change line 1416 in alttoolbar_type.py from

self.searchbar.set_search_mode(search_button.get_active())

to

self.searchbar.set_search_mode(True)

Does this work better?

**Comment by djh101** [comment]
Everything is working great now :). (I guess I should close this issue.) Thank you for all your help (this plugin has helped sever one of my last attachments to Windows).

**Comment by fossfreedom** [comment]
ok - ta.  I've added the fix to the repository.
