### ISSUE TITLE
Vertically Arranged Column Browser

### ISSUE THREAD

**Issue by djh101** [fossfreedom/alternative-toolbar#76]
Left-to-right column browser wastes a lot of space. Personally, I would much prefer a top-to-bottom column browser.

**Comment by fossfreedom** [comment]
Thanks for raising the issue.

I need you to mock up what you mean - can you grab a screenshot and change stuff around to show me what you are referring to and how you think stuff should look like?

**Comment by djh101** [comment]
![rhythmbox_columns](https://cloud.githubusercontent.com/assets/5396418/12538476/28f30bae-c28f-11e5-99fe-ed83c877fb51.png)

Here you go, and thank you.

**Comment by fossfreedom** [comment]
![ubuntu xenial snapshot 2 running - oracle vm virtualbox_117](https://cloud.githubusercontent.com/assets/996240/12538571/d1132f4a-c2d4-11e5-919d-862908247d03.png)

Yep - its certainly possible.

If you use Gtk Inspector to view the objects behind rhythmbox - you can change the "orientation" of the Gtk Paned object which is the object holding the browser & tracks to be horizontal.

Then you can look at the main RBLibraryBrowser object and again change the orientation - this makes the browser objects as you see it.

Implementation:

1. add an option to the plugins preferences window to allow the user to select horizontal/vertical for the categories - save this in gsetting
2. retrieve this value with the other gsettings values in alternative-toolbar.py
3. add a new method to on_page_change (alternative-toolbar.py) to reset the page-view
4. add a page-view method to alttoolbar_type.py 

  - using the find method on alttoolbar_type search for the GtkPaned object (this is the browser+tracks entry view objects)
  - change the orientation of this object
  - get the first child of the GtkPaned (this is the browser) - change the orientation

There you go - fancy having a stab at implementing the above?

**Comment by djh101** [comment]
Sure, I'll give it ago (as soon as I can find a little bit of free time to do so). Thanks.

**Comment by fossfreedom** [comment]
@djh101 - the above commit adds a new option which should get this functionality.

Note - before testing please wait until I've resolved #79

**Comment by fossfreedom** [comment]
@djh101 - ok - temporarily backed out #79 so it should be safe to test now.

**Comment by djh101** [comment]
Perfect! And thank you for the quick response time. Everything looks great now. :)
