### ISSUE TITLE
Some of the sidebar symbolic icons don't make sense.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#8]
I know this is not a headerbar thing, but like I said - the brushing I am planning goes beyond the scope of the CSD.
Anyways, look at the this screenshot:
![screenshot from 2015-03-15 01 44 45](https://cloud.githubusercontent.com/assets/1658870/6654061/2853e196-cab5-11e4-88bd-1fd893f900c2.png)
First - "Play queue" uses documents icon. It should use custom symbolic icon, because there is no queue one in the icon themes.
Second - "Import errors" misses an icon and it should use - "dialog-error-symbolic.svg" icon.
Third - "libre.fm" service icon is very similar to wifi logo, so it should use "network-wireless-symbolic.svg"
Fourth - "Radio" needs a custom symbolic icon, because icon sets don't come with radio symbolic icons. Using a server symbolic icon is really confusing. I can do one.
Fifth - playlists should not look a search symbolic icon, but custom icons for the three default ypes of playlists. I will do them. a playlists icon. Also - for user created list a playlist icon should be used. Alas for some odd reasons iconsets don't ship with such icon, so I will have to do a custom one.

**Comment by fossfreedom** [comment]
correct - this goes beyond this particular plugin.

Three ways to address this.  Obviously, upstream via a pull request to rhythmbox itself.  The maintainer prefers coders and patches.  I've noted that enhancement requests rarely get actioned - someone has to do the work before Jonathan Matthew (the maintainer) would consider pulling in the patch.

The second is distro specific - make those changes in the source itself and maintain the patches for every new rhythmbox version...

The third way is more speculative but possibly via another plugin - each of those options in the picture is in a RB.DisplayPageTree

 - https://lazka.github.io/pgi-docs/#RB-3.0/classes/DisplayPageTree.html#RB.DisplayPageTree

Every item is ultimately a RB.DisplayPage (i.e. playlists etc are derived from RB.DisplayPage)

 - https://lazka.github.io/pgi-docs/#RB-3.0/classes/DisplayPage.html#RB.DisplayPage

There is a property on the page called icon - its a Gio.Icon - so it should be possible (at least in theory) to assign your own Gio.Icon to it.

As I said - the third way is more speculative - not sure what event that could be used to tap into, to detect when a new RB.DisplayPage is created and then override the icon.

**Comment by me4oslav** [comment]
Right, way one seems like the best option. I can do the icons, you can do the implementation work and send a pull request. But there is a but. Is the maintainer interested in merging cosmetics patches like this one?
I didn't get the second way.
Third way seems like last resort method, so I guess it should be avoided if possible.
I will do the icons right now.

**Comment by fossfreedom** [comment]
@me4oslav 

  C programming isnt generally my forte - its been a while.  Happy to give it a try though.

As to whether the maintainer of rhythmbox is interested - I've posted this bug report to sound him out.

 - https://bugzilla.gnome.org/show_bug.cgi?id=746235

**Comment by me4oslav** [comment]
Commended there. I am now working on this:
https://github.com/fossfreedom/alternative-toolbar/issues/4
Would you prefer pen and paper wireframes or digital ones?

**Comment by fossfreedom** [comment]
web-links to the "-symbolic.svg" files themselves.

**Comment by me4oslav** [comment]
No, no, I know abut the icons. :)
I was asking around the wireframes for issue #4 - do you want them digital or would you prefer them as sketches?

**Comment by fossfreedom** [comment]
sketches would be fine.

**Comment by me4oslav** [comment]
As a person that die a little on the inside when he has to do digital wireframes and/or mockups I can't thank you enough for not making me do such. :)

**Comment by me4oslav** [comment]
Here is the tarball with the needed icons:
https://dl.dropboxusercontent.com/u/2656555/rb-symbolic-icons.tar.gz

When implementing them please put them in the same scalable subfolders as they are in the tarball and don't change the names. The folders structures and naming are XDG Gnome standards approved, so icon themes can theme them.

Rationale:
"Play queue" - "mimetypes/audio-x-queue-symbolic.svg" (in the tarball).
"Import errors" -  "dialog-error-symbolic.svg" (no need for a custom icon).
"libre.fm" - "apps/librefm.svg" (in the tarball)
"Radio" - "devices/audio-radio.svg" (in the tarball).
"User created playlist" - "mimetypes/audio-x-playlist-symbolic.svg" (in the tarball).
"Top rated playlist" - "user-bookmarks-symbolic.svg" (no need for a custom icon).
"Recently added playlist" - "mimetypes/audio-x-playlist-recently-added-symbolic.svg" (in the tarball).
"Recently played playlist" - "mimetypes/audio-x-playlist-recently-played-symbolic.svg" (in the tarball).

Everything else is fine.

GTK doesn't need the ".svg" suffix when you're going to implemented those.

**Comment by me4oslav** [comment]
Do we need this issue still open?

**Comment by fossfreedom** [comment]
guess not.
