### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by m110s** [fossfreedom/alternative-toolbar#84]
Is it possible to add option to force use of dark theme for rhythmbox?
Quodlibet, for example, has that option in Theme Switcher plugin.

**Comment by fossfreedom** [comment]
anything is possible.

Any ideas where the source code for the "theme switcher plugin" resides? - need to have a quick look at what it does.

**Comment by fossfreedom** [comment]
think this is the code you are referring to:

 - https://searchcode.com/codesearch/view/8725625/

**Comment by m110s** [comment]
Yes, that's the code of Theme Switcher plugin. You are really fast. :)

**Comment by fossfreedom** [comment]
not sure I'm following the code - does quodlibet allow you to specify the theme for the application?

Seems like a very strange idea.

This bit of the code looks like it does the "pref dark theme" step depending upon whether the user has clicked the checkbox/switch or whatever:

<pre>
  def __set_dark(self, value):
        if not self.__enabled:
            return
        settings = Gtk.Settings.get_default()
        if value is None:
            value = self.__default_dark
        settings.set_property('gtk-application-prefer-dark-theme', value)
</pre>

Have you dabbled in any python coding?  If yes - happy to help you with creating a patch for the above.

**Comment by m110s** [comment]
Here is screenshot of TS options from Quodlibet:
![screenshot from 2016-03-17 13-29-46](https://cloud.githubusercontent.com/assets/5939323/13846199/b062536c-ec45-11e5-9439-160953a87a67.png)
Regarding programming, I can't help because I'm not programmer.

**Comment by fossfreedom** [comment]
ok - no worries

Can confirm that if you add the following two lines to alttoolbar_type.py line 198

        settings = Gtk.Settings.get_default()
        settings.set_property('gtk-application-prefer-dark-theme', True)

You'll get the dark theme - just really need to wrap that up into a user configurable option

![Imgur](http://i.imgur.com/CLDAtdb.png)

**Comment by m110s** [comment]
I've just tried your quick fix and I can confirm that works!
Looking forward for full implementation.
Thanks a lot!

**Comment by fossfreedom** [comment]
this should now be in the release candidate.

**Comment by m110s** [comment]
I've just tried new git version and option is there.
Thanks mate!
