### ISSUE TITLE
"Play Queue in Side Pane" option doesnt work anymore

### ISSUE THREAD

**Issue by scheurneus** [fossfreedom/alternative-toolbar#85]
Hi,

I really like this plugin, however I am annoyed by the fact that the "Play Queue in Side Pane" option doesn't work anymore, because I really like that function and it makes making a play queue way more convenient.
##

**Comment by fossfreedom** [comment]
For the moment, disable the enhanced sidebar in the preferences for the plugin.

**Comment by scheurneus** [comment]
@fossfreedom thanks, even though that wasn't even necessary, the only thing that happened was the queue was resized to be invisible.

**Comment by fossfreedom** [comment]
Strange. Ok thanks for the feedback

**Comment by fossfreedom** [comment]
appears to work ok now.
