### ISSUE TITLE
Issues with Radio tab

### ISSUE THREAD

**Issue by vrishab** [fossfreedom/alternative-toolbar#87]
Some nice work with the rhythmbox interface. But, I have a couple of issues with the radio screen:
1. Cannot add new radio station.
2. In radio screen, "Stations / Categories"  become "Songs / Categories" when toggled. It should be "Stations / Categories" always.
##

**Comment by vrishab** [comment]
This was on 0.17.1

**Comment by fossfreedom** [comment]
Ctrl + t to display the source toolbar to add stations

**Comment by fossfreedom** [comment]
Re second issue. Sounds logical. Happy to receive a pull request

**Comment by fossfreedom** [comment]
first issue - made this an always on toolbar - same as podcasts
