### ISSUE TITLE
Restart the player for changes to take effect.

### ISSUE THREAD

**Issue by vrishab** [fossfreedom/alternative-toolbar#89]
This should not be displayed unless the user has changed something. This plugin software is the only place where I have seen this. So this looks odd. Please check with gnome HIG.

**Comment by vrishab** [comment]
Also, I am not sure if the player needs restart for every possible change in settings. it is kind of annoying. The player should be restarted only when necessary.

**Comment by fossfreedom** [comment]
Sorry. Nothing I can do about this.  The plugin does weird and wonderful stuff to gtk objects to move stuff around.
