### ISSUE TITLE
(rhythmbox:1726): libpeas-WARNING **: Could not find plugin 'rb' for plugin 'alternative-toolbar'

### ISSUE THREAD

**Issue by bmeznarsic** [fossfreedom/alternative-toolbar#9]
Hi!
I get an error when trying to enable alternative-toolbar from the plugins dialog. What am I missing?
(rhythmbox:1726): libpeas-WARNING **: Could not find plugin 'rb' for plugin 'alternative-toolbar'
I got the code from the master branch (commit 2dd420d037ffc88c48e397be6b501d55167227aa) and installed it on Evolve OS beta 1.1 (https://github.com/evolve-os).
Thanks!

**Comment by fossfreedom** [comment]
hmm.

That's not a distro that I'm aware of - is it based upon another distro (if so what distro and version?) or is it a unique distro by itself.  What version of rhythmbox are you running?

the rb plugin is a standard but hidden plugin if you have rhythmbox fully installed.  In debian/ubuntu this is part of the rhythmbox-plugins package

b is a system plugin - it should have been installed automatically with a new install or an upgrade.

Is this a standard install? Have you installed/compiled rhythmbox manually or is this a minimal installation with a reduced set of packages

you'll see the rb plugin in /usr/lib/rhythmbox/plugins/rb on Ubuntu/Debian

is the above folder visible and contains the following?

/usr/lib/rhythmbox/plugins/rb$ ls
Coroutine.py  __pycache__  rb.plugin  stringmatch.py
Loader.py     rbconfig.py  rb.py      URLCache.py

**Comment by bmeznarsic** [comment]
It's a unique distribution and I installed it from their main repository. I'm running version 3.1 according to the package manager:
"$ sudo eopkg blame rhythmbox
Name: rhythmbox, version: 3.1, release: 2
Package Maintainer: Ikey Doherty <ikey@evolve-os.com>
Release Updater: Ikey Doherty <ikey@evolve-os.com>
Update Date: 01-17-2015

Update to 3.1"

Dunno if the pspec.xml file could be of any help to you https://github.com/evolve-os/repository/blob/08f2c1970aad286c0b49ba5dcaa3491847247af6/desktop/gnome/rhythmbox/pspec.xml

I checked the directory and it is not present/visible.

I can't tell you much more. I think I'll report it downstream and see what's up with that rb plugin.

Thanks for your help!

**Comment by fossfreedom** [comment]
that pspect looks rather short.  There  should be quite a few plugins (20 folders or more) listed under /usr/lib/rhythmbox/plugins including the rb plugin.

Please let me know what you find out.

**Comment by bmeznarsic** [comment]
Will do!

**Comment by bmeznarsic** [comment]
Here's the the bug report https://evolve-os.com/project/os/issues/OS-134
I just issued it...

**Comment by ikeydoherty** [comment]
Jumping in here..

The list is recursive includes, so it wouldnt have one for every plugin.

I believe this is more likely a Python 3 issue with our Rhythmbox package.

**Comment by fossfreedom** [comment]
@ikeydoherty 

  the error message means that it cannot find the python file rb.py 

In ubuntu this exists in /usr/lib/rhythmbox/plugins/rb

Where is this same file in evolve?  It needs to be in a folder location that rhythmbox & libpeas can find

**Comment by ikeydoherty** [comment]
It doesn't exist. Definitely an issue our end.. Will update you shortly if I get it fixed..

**Comment by fossfreedom** [comment]
closing.  This is not an issue with the plugin.
