### ISSUE TITLE
Icons for Help / About

### ISSUE THREAD

**Issue by vrishab** [fossfreedom/alternative-toolbar#90]
![screenshot from 2016-08-05 08-59-23](https://cloud.githubusercontent.com/assets/8469504/17425561/409f5f96-5aec-11e6-8d0e-dff99aefc5fe.png)

Only use icons whose meaning is commonly recognized.  ( Gnome HIG: https://developer.gnome.org/hig/stable/icons-and-artwork.html.en ). Please refer to icons at /usr/share/icons/gnome/32x32/actions. There are icons for Help / About which are quite standard.
##

**Comment by vrishab** [comment]
The icons for About / Help in plugin setting window is confusing. I have not seen them anywhere. Settings icon is fine.

**Comment by fossfreedom** [comment]
Code is the plugins module.  Happy to receive pull requests

**Comment by fossfreedom** [comment]
neither help nor about have common symbolic icon equivalents for themes.

**Comment by vrishab** [comment]
/usr/bin/gtk3-icon-browser ( package: gtk-3-examples )

Search for "help"

**Comment by fossfreedom** [comment]
ok - ta - I see a ? for help and the same for help about "help-about-symbolic"

help-contents-symbolic is an alternative - document type symbol with a ? in the middle.

**Comment by vrishab** [comment]
http://imgur.com/a/L3t9m

I think the help symbolic icons can be better. I will raise a bug in gnome.

**Comment by vrishab** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=770560
