### ISSUE TITLE
User local installable plugin

### ISSUE THREAD

**Issue by vrishab** [fossfreedom/alternative-toolbar#91]
I try out most rhythmbox plugins in /home/${USER}/.local/share/rhythmbox/plugins/.

For testing the latest changes in git I don't prefer to disturb /usr, as would most other users. If possible, please make the plugin to be installable in /home/${USER}/.local/share/rhythmbox/plugins/.
##

**Comment by fossfreedom** [comment]
Makefile will need a local option.  Happy to receive pull requests
