### ISSUE TITLE
Enhanced sidebar loads after a delay

### ISSUE THREAD

**Issue by vrishab** [fossfreedom/alternative-toolbar#93]
When rhythmbox is started after enabling "alternate-toolbar", the enhanced sidebar loads late ( 2 seconds ). The sidebar is blank for a couple of seconds. This looks odd. The old sidebar used to load quick.

**Comment by fossfreedom** [comment]
Again, nothing I can do about this. I have to wait I until rb is fully up and running before making changes to the gui

**Comment by vrishab** [comment]
Is it possible to display the entire rhythmbox window after "alternate toolbar" is loaded.

**Comment by fossfreedom** [comment]
not sure what you mean - windows maximize button?
