### ISSUE TITLE
Stop after current song

### ISSUE THREAD

**Issue by OceanWolf** [fossfreedom/alternative-toolbar#96]
I really miss a stop after current song feature in Rhythmbox.

What do you think, should it go here, or in a separate plugin?

P.S. I programme python, but I don't have the time to commit right now to learn how to do so for Rhythmbox, one day soon I hope.

**Comment by fossfreedom** [comment]
there are a couple of plugins written for the older RB (pre 3.0) - I would suggest forking and uplifting these to re-add this feature. (41 and 42 here https://wiki.gnome.org/Apps/Rhythmbox/Plugins/ThirdParty)

**Comment by OceanWolf** [comment]
Thank you, I shall take a look at it, number 42 looks more generic (and besides, we all know from the great book that the answer is 42), so I shall try with that, though it looks like a fork of 41 which you and @srijan worked on, only a few lines different... but it hasn't been forked by git, but I see from the history of 42, and https://github.com/radus/rhythmbox_stop_after_track/issues/1, that they were originally quite different, but 42 grew towards 41 at your suggestion...
