### ISSUE TITLE
Ctrl-F only focuses on the search field if it's already visible

### ISSUE THREAD

**Issue by Pointedstick** [fossfreedom/alternative-toolbar#98]
If you click on the magnifying glass button, the search bar pops down, and then Ctrl-F focuses on the search field, like it should.

But if you hit Ctrl-F before exposing the search bar, it either does nothing or opens a tiny little search field somewhere else.

**Comment by fossfreedom** [comment]
clicking somewhere on the source pane should be enough e.g. clicking on a track to give the source pane focus.

**Comment by Pointedstick** [comment]
It isn't. When I do that, a tiny little search bar appears below the source pane:

![not right](https://cloud.githubusercontent.com/assets/1097249/21194387/1036243a-c1ed-11e6-87f0-5e1512c45d33.png)


Regardless, it would be nice it Ctrl-F would make the search bar appear irrespective of what has focus. That's the way Rhythmbox works without this plugin, which I greatly prefer.

I'm using GNOME 3.22 on Fedora 25 with Wayland.

**Comment by fossfreedom** [comment]
k - yep can confirm the issue.

**Comment by McSinyx** [comment]
I've come up with an implementation at 16fb1cf which also fixes the the bug that search entry is not focused the second time it is toggled by the search button (or Ctrl-f). However, there are a few remaining problem I'd like to have your advice on:

* While the entry is focused, Ctrl-f seems to be bound to select all search terms (to search for new track I guess). While Escape in this case can be use to hide the searchbar, there is another problem:
* Cancelling search via Escape doesn't make the search bar to emit `hide` signal, hence I cannot find a way to explicitly handle this case. Currently, when escaped is pressed, the entry disappears, but the button is not toggled back to inactive state. I've been digging in PyGObject doc this entire day without any luck finding the right signal.

**Comment by fossfreedom** [comment]
escape is handled via monitoring the main window keypress event

https://github.com/fossfreedom/alternative-toolbar/blob/8b99ef42aacb65340e0527c7660ab16d54816937/alttoolbar_type.py

line 1334 and the subsequent _on_key_press method

pressing escape sets_active the search button to false

**Comment by fossfreedom** [comment]
odd that escape and ctrl+f still works after commenting out.

Off the top of my head the only weird source is Sound Cloud - so whatever changes still needs to accommodate that source.

**Comment by McSinyx** [comment]
> odd that escape and ctrl+f still works after commenting out.

So I guess we'll need to proceed with my ugly proposal. One additional queestio: in non-CSD mode, the search entry is in source toolbar (the Ctrl-t thing) - is there a way to get this entry (sorry I'm new to Gtk+)?

> Off the top of my head the only weird source is Sound Cloud - so whatever changes still needs to accommodate that source.

What do you mean?

**Comment by fossfreedom** [comment]
![untitled](https://user-images.githubusercontent.com/996240/46298146-42209d00-c596-11e8-84a8-553e5c27626f.png)

So in soundcloud you see that the search button display much more than just a search entry

https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_controller.py#169

Its a horrible kludge - but basically we have to iterate through all the objects in the source until you find a RBSearchEntry ... Then within the RBSearchEntry object you iterate through that until you find the GTKEntry.

**Comment by McSinyx** [comment]
Sorry, the postfix should have been `#L169` (just clicking on the line is easier I think).

I'll try to maintain compatibility for Sound Cloud, but the non-CSD seems to be the most problematic one right now. I'll return if I have more question, thank you.
