### ISSUE TITLE
Display Browse Categories horizontally or vertically

### ISSUE THREAD

**Issue by MichaelTiebesl** [fossfreedom/alternative-toolbar#99]
I'm currently using Rhythmbox on Solus OS.
Before on Ubuntu 16.10 I saw the option to display browse categories horizontally or vertically.
Unfortunately i can't see that option using Rhythmbox on Solus OS.
Do i miss something or is it simple not there the option?

Thanks

**Comment by fossfreedom** [comment]
Make sure you are running the very latest version. Maybe solus is carrying an old version in their repository?

**Comment by MichaelTiebesl** [comment]
I think you are right. 
According to the website it is in Solus rhythmbox-alternative-toolbar-0.16.3. instead of 0.17.3
Hopefully that will fix the issue. I already created a ticket for it with Solus.
Thanks for your time.
